### ISSUE TITLE
Can I use this for Character level LM ?

### ISSUE THREAD

**Issue by pdcoded** [kpu/kenlm#100]
Is Character level implementation possible using this?

**Comment by sumantk** [comment]
It is possible, but may not be clean. You have to change the input data.  If we want to keep track of word boundaries, we also have to replace space at the end of each word by a special character. Then, we will have to treat each char as the token (word) and separate them by spaces. Now, we can train the model.

**Comment by pdcoded** [comment]
Thanks but do I need to change anything in the command line for kenlm binary creation other than preprocessing? So if there is a sentence "hey I am good" - It becomes "h e y $ I $ a m $ g o o d"

**Comment by kpu** [comment]
You can do a character model.  But might want --discount_fallback because there will likely be no singleton unigrams.
