### ISSUE TITLE
Cannot pickle language model

### ISSUE THREAD

**Issue by jbingel** [kpu/kenlm#101]
I have a kenlm model that I'd like to pickle (because it's part of a larger object that I want to pickle...). The following minimal example fails:

```
import kenlm, pickle
lm=kenlm.LanguageModel("my_lm.bin") 
with open('lm.pickle', 'wb') as pf:
    pickle.dump(lm, pf, pickle.HIGHEST_PROTOCOL)
```

The following error is thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "kenlm.pyx", line 258, in kenlm.Model.__reduce__ (python/kenlm.cpp:3929)
NameError: name '_kenlm' is not defined
```

Any help? I'm on Python 3.5.2 (Anaconda), kenlm 0.0.0 installed via pip.

**Comment by jbingel** [comment]
I now manually installed kenlm from here: https://github.com/vchahun/kenlm. This solved my problem (after having to adapt my code because of different signatures of  `LanguageModel.score()`), but whatever the reason for the problem in the pip-ed version, I guess that should be fixed or pointed out.

**Comment by kpu** [comment]
Hopefully that fixed things.  One line change to kenlm.pyx, but cython generated a big change.
