### ISSUE TITLE
Tokenization?

### ISSUE THREAD

**Issue by mattkleonard** [kpu/kenlm#103]
In the Corpus Formatting Notes, it states that the input data should be tokenized. I'm unclear what the actual formatting of the input text should be. Is it sufficient to have each sentence on a separate line? Does each sentence need to be word tokenized?

Thank you

**Comment by kpu** [comment]
It's generally good practice to tokenize first so that "foo," turns into "foo ," instead of treating these as separate words.  However, nobody can agree on what the exact tokenization rules should be.  https://github.com/kpu/preprocess has some stuff based on the Moses tokenizer.
