### ISSUE TITLE
Can't train n-gram LM from large corpus

### ISSUE THREAD

**Issue by mattkleonard** [kpu/kenlm#104]
The input text file is 12GB, so large, but I don't think unmanageably massive.
Here's the error:

```
bin/lmplz -o 5 -S 80% -T /tmp </Users/mattleonard/Documents/Python/language_models/wikipedia/wikitext_split.xml >/Users/mattleonard/Documents/Python/language_models/wikipedia/wikitext_split.arpa
=== 1/5 Counting and sorting n-grams ===
Reading stdin
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
*****************Last input should have been poison.
util/file.cc:220 in void util::WriteOrThrow(int, const void *, std::size_t) threw FDException because `ret < 1'.
Invalid argument in fd 4 while writing 5651839480 bytes
Abort trap: 6
```

I should add that the same thing happens when training a trigram model.

**Comment by mattkleonard** [comment]
I'm re-upping this issue.

Since originally posting, I've tried a few other things, and am still getting the error.

Is it related to memory? I tried cutting my corpus in half and now it gets to ~55% (instead of ~25%) before throwing the "poison" error.

Thanks,

Matt

**Comment by kpu** [comment]
Ran out of disk space?  That or OS X didn't like when it tried to write 5 GB in a single go.  Also could be the filesystem has a limit on file size.  What kind of filesystem is /tmp ?

**Comment by ritwikmishra** [comment]
So how much disk space is needed (approx) if size of the corpus is G gigs, S sentences, and T1 unique unigram tokens? I have 3TB of free space but it still shows me this error when I want to train the model on 21GB text corpus with 63.1M sentences and 1.86B tokens. Why?

**Comment by v-yunbin** [comment]
@ritwikmishra have you  solve the problem？
