### ISSUE TITLE
Can't build on 32 bit machine

### ISSUE THREAD

**Issue by yariv-c** [kpu/kenlm#105]
When building for ARM 32bit I get this compilation warning:

`usr/include/kenlm/util/probing_hash_table.hh: In static member function 'static std::size_t util::Power2Mod::RoundBuckets(std::size_t)':
usr/include/kenlm/util/probing_hash_table.hh:68:23: error: right shift count >= width of type [-Werror=shift-count-overflow]
       from |= from >> 32;`

When I use the compiled code with a model that was built on a 64bit machine I get nan scores.

**Comment by kpu** [comment]
Hmmm that's not good.

**Comment by yariv-c** [comment]
Thanks for the solution.
