### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by LP-MSFollower** [kpu/kenlm#106]
I am very sorry to disturbing you. But I meet the problem while running the ' example.py '. The problem is that "ImportError: No module named 'kenlm".  So, can you give me some ideas to solve the problem ? Thank you very much for your help.

**Comment by yangbisheng2009** [comment]
Did you have run 'python setup.py install'?

2017-10-16 23:55 GMT+08:00 LP-MSFollower <notifications@github.com>:

**Comment by kpu** [comment]
I agree with @yangbisheng2009 .  Did you install it?
