### ISSUE TITLE
Boost

### ISSUE THREAD

**Issue by purplelive** [kpu/kenlm#108]
Hi, i have the problem below when i try  build and download boost, i dont know why that happened, an you point me ?

failed gcc.compile.c++ bin.v2/libs/log/build/gcc-5.4.0/release/link-static/threading-multi/format_parser.o...

./b2
sudo ./b2 install

bjam

**Comment by kpu** [comment]
Not a kenlm bug.  Try a newer version of Boost?

**Comment by purplelive** [comment]
...failed gcc.compile.c++
bin.v2/libs/python/build/gcc-5.4.0/release/link-static/threading-multi/object/pickle_support.o...

i have this problem with boost, btw  use the latest version boost_1_65_1.

can you point me with this problem.

On Mon, Oct 23, 2017 at 12:26 AM, Kenneth Heafield <notifications@github.com
