### ISSUE TITLE
Can lmplz estimate model that <unk> probability is 0?

### ISSUE THREAD

**Issue by 625tk** [kpu/kenlm#109]
Hi,
I compare different LMs. I want to create closed vocabulary model.

Can `lmplz` estimate model that < unk > probability is 0?

**Comment by kpu** [comment]
I never did get around to implementing that...

**Comment by 625tk** [comment]
I thought that is one of the solutions to estimate model that training corpora include <unk> tokens.
I consider other solutions.
Thank you.
