### ISSUE TITLE
No attribute 'State' for `kenlm.State()` python wrapper

### ISSUE THREAD

**Issue by xxks-kkk** [kpu/kenlm#117]
I try to run the python example.py and the following error raised.

```
>>> kenlm.State()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'State'
```

I'm not sure if there is any special care when I install the python package. I run `python setup.py install`, which is from the guide [here](http://victor.chahuneau.fr/notes/2012/07/03/kenlm.html).

**Comment by AhmedESamy** [comment]
Check where you got your source code. Uninstall your current version, and follow instructions here https://github.com/kpu/kenlm/blob/master/README.md to download and install.
