### ISSUE TITLE
Need suggestion : Input file format for training

### ISSUE THREAD

**Issue by manishbansal-fk** [kpu/kenlm#119]
What should be input file format for training. I am having one sentence per line in a file with "\n" at the end of each line and training command looks like "**bin/lmplz -o 4 <train.csv >dummy.arpa**"

Does newline or "\n" create any problems while training as we don't have access to vocab for LanguageModel in **python** wrapper.

**Comment by kpu** [comment]
I'm assuming you mean ASCII character 10 newline, not the literal string \n.  This is how it's intended to operate.  

You can always check the vocabulary by looking at the unigram section of the ARPA file.  

Not sure why your text file has a .csv extension.

**Comment by manishbansal-fk** [comment]
Thanks for quick update :) 

i) While preparing data for training, I am doing like this in python,
   `with codecs.open(file_loc, mode='w', encoding='utf-8', errors='ignore') as f1:   
        f1.write("hello" + "\n")`
   Is this same as ASCII character 10 newline ? As opening file doesn't show \n as string literal.
   File output : 
   hello

ii) I am new to Language Model & ARPA file format. Could you please point to some relevant python code / doc to access vocab from ARPA file.

iii) CSV file extension was ambiguous. It just contains all training sentences, each sentence per line.

iv) Could you please explain how can we train LM with ngram-count in python, e.g. File with following data 
    hello    15
    world    200
    OR repeating sentence by their count would suffice here. But its very difficult when count is in range of million.

**Comment by kpu** [comment]
Yes, the new lines are fine.  

Just open the ARPA file with less.  Unigrams come first, so you'll see lots of log_prob unigram backoff entries.  

I don't support training from ngram counts because really the only use case is count files that have been thresholded.  Which breaks Kneser-Ney.  

If you're referring to the cute-and-tiny Google n-grams, here's a lot more data: http://statmt.org/ngrams/

**Comment by manishbansal-fk** [comment]
Thanks once again :) Your work looks very exciting 👍 

- I was referring to http://data.statmt.org/ngrams/lm/ (en.trie.xz) for english language, but this is very huge in size (~3.4TB). Does there exist any tiny LM for english from common crawl.

- I was trying to handle count by training model with instance repetition, but getting below error (training data size ~ 4.6GB)

Error stack-trace : 
**=== 1/5 Counting and sorting n-grams ===
Reading stdin
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:553092 2:5325077504 3:9984520192 4:15975232512
/home/manish.bansal/kenlm/lm/builder/adjust_counts.cc:42 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts() threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 4-grams with adjusted count 2 because we didn't observe any 4-grams with adjusted count 1; Is this small or artificial data?
Aborted**

- What is the advantage of **Moses** over training normally with (bin/lmplz -o 3 > LM.arpa => bin/build_binary LM.arpa LM.klm), Would this help for above case.

**Comment by manishbansal-fk** [comment]
@kpu it would be great help if you could give some further pointers. Thanks a lot :)

**Comment by manishbansal-fk** [comment]
@kpu Please share your thoughts.
