### ISSUE TITLE
bin/./lmplz: No such file or directory

### ISSUE THREAD

**Issue by phanlong95** [kpu/kenlm#122]
/bin/bin/./lmplz --text vocabulary.txt --arpa  words.arpa --o 3

````````````````````````````````````````````````````````````
lmplz: No such file or directory
Where can i find lmplz ? -.-

**Comment by kpu** [comment]
Did you compile it as per the directions in README.md?  It should then be in `kenlm/build/bin/lmplz`.  

Where did you get the path /bin/bin/. from?

**Comment by phanlong95** [comment]
yes i did.
mkdir -p build
cd build
cmake ..
make -j 4
``````````````
but i can not find lmplz .

**Comment by phanlong95** [comment]
cmake error configuring incomplete errors occurred !!!
why -.-

**Comment by kpu** [comment]
Post the complete output of the commands you ran above.

**Comment by kpu** [comment]
Reopen when you have output.

**Comment by lvjiujin** [comment]
this problem is easy,because, your enviromental vairable  is not confgired, you can do like this:
vi .bashrc
in the last line of the line 
you add the " export PATH=/ROOT/kenlm/build/bin:$PATH "
after this doing:
source .bashrc

**Comment by Nishant-Pall** [comment]
> this problem is easy,because, your enviromental vairable is not confgired, you can do like this:
> vi .bashrc
> in the last line of the line
> you add the " export PATH=/ROOT/kenlm/build/bin:$PATH "
> after this doing:
> source .bashrc

Can you please explain the exporting of Path, I'm new to Linux and perhaps an example might help
