### ISSUE TITLE
A large amount of free space on the hard disk is requested

### ISSUE THREAD

**Issue by VictorBebnev** [kpu/kenlm#127]
Hello. I have an issue with creating .arpa file from the corpus with 51gb size (downloaded from [here](http://data.statmt.org/ngrams/deduped_en/)). The script (bin/lmplz) requires 400Gb+ of free disk space. Could you please help me, do we have possibility for using less memory?

**Comment by kpu** [comment]
Intermediate data compression hasn't been implemented (and probably won't be, the way neural models are going).  If it's the size of the ARPA itself, you can always pipe directly to build_binary.  

It will also use less disk if your glibc is new enough to support `fallocate` with `FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE` options.  (Rumor has it this is glibc 2.18 and newer).

**Comment by VictorBebnev** [comment]
Thanks for fast answer. Tell me please, how much free space is required for .arpa file, if the source file is N GB?

**Comment by VictorBebnev** [comment]
The problem is that at the first step the script allocates 200 GB on the second 200 GB more on 3, the free space ends, and the script falls.
Log:
Quantization is only implemented in the trie data structure.
=== 1/5 Counting and sorting n-grams ===
Reading /export/en.00.deduped.clean
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
**Warning: </s> appears in the input.  All instances of <s>, </s>, and <unk> will be interpreted as whitespace.
**************************************************************************************************
Unigram tokens 8892056476 types 200012480
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:647025216 2:1725400576 3:3235126272 4:5176201728 5:7548627456
Statistics:
1 200012480 D1=0.85071 D2=1.05781 D3+=1.20183
2 276042833/1252115166 D1=0.837555 D2=1.05342 D3+=1.22521
3 551035893/3342844163 D1=0.874215 D2=1.10515 D3+=1.25211
4 578734960/5308152842 D1=0.917598 D2=1.17416 D3+=1.28965
5 442030459/6376109268 D1=0.916155 D2=1.3082 D3+=1.33019
Memory estimate for binary LM:
type    GB
probing 43 assuming -p 1.5
probing 52 assuming -r models -p 1.5
trie    27 without quantization
trie    18 assuming -q 8 -b 8 quantization 
trie    23 assuming -a 22 array pointer compression
trie    14 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:710976064 2:1895936128 3:3554880256 4:5687808512 5:8294720512
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
***######################################---Last input should have been poison.
Last input should have been poison.
Last input should have been poison.

**Comment by kpu** [comment]
There is no straightforward function from input file size since it depends on the number of unique ngrams. However, I note you have a number of n-grams.  Each unique n-gram takes 4*n+8 bytes.  Double that for streaming input and output.  There's also a side file of 4 bytes per n-gram except those of highest order.

**Comment by dalonlobo** [comment]
Hello, I'm running into similar problem, I will try to increase the disk space and try. 
Is there a specific reason for this error message "Last input should have been poison", since it is thrown when its out of memory?

**Comment by Sanjeev2487** [comment]
Hi @kpu ,
My corpus is 55GB and I tried generating trie binary as following:
`bin/lmplz -o 5 --vocab_estimate 400000 --prune 0 1 1 1 1 -S 80%  <corpus.txt | bin/build_binary trie -a 22 -q 8 -b 8 -S 80% /dev/stdin lm.bin`
I have enough memory which might be required but I git the following error 
`Reading corpus.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
******************************End of file Byte: 0
ERROR
`
