### ISSUE TITLE
Can not find neuralLM.h

### ISSUE THREAD

**Issue by Samurais** [kpu/kenlm#133]
I am trying to build nplm.cc, it fails due to "can not find neuralLM.h", I know it is in progress. 
how is it going? can you provide this neuralLM.h as well?

**Comment by kpu** [comment]
You'll need to write the build system rules yourself, but compile against this: https://github.com/kpu/nplm .  It's a now-stale fork of NPLM.

**Comment by Samurais** [comment]
Great, thanks.
