### ISSUE TITLE
[cpp] Get random BaseScore with the same code and data

### ISSUE THREAD

**Issue by Samurais** [kpu/kenlm#134]
# Description
After integration kenlm into my build system, I get a problem with the BaseScore method, **it returns random float**. 

## Model
The model file is generated with 
```
lmplz -o 2 <text.txt >model.arpa
```

Headers
![image](https://user-images.githubusercontent.com/3538629/37241424-c67e22a6-2493-11e8-96d3-670e22d39785.png)

## Init Model Object
```
bool SenscoreMW::init(std::string& model_file_path)
{
    VLOG(3) << "init " << model_file_path;
    config_.load_method = util::POPULATE_OR_READ;
    const char* file = model_file_path.c_str();
    model_ = lm::ngram::LoadVirtual(file, config_);
    vocab_ = &(model_->BaseVocabulary());
    VLOG(3) << "state size:" << model_->StateSize();
    return true;
}
```

trace

![image](https://user-images.githubusercontent.com/3538629/37241290-02897d10-2492-11e8-888e-c038090c7914.png)

Note, I have printed some info for debugging. From the log, I think it is inited successfully.

## sentence scorer class
Get the score of a sentence with ```BaseScore```.

```
float SenscoreMW::score(const std::vector< std::string>& words)
{
    lm::ngram::Model::State state;
    lm::ngram::Model::State out;
    float ret;
    double corpus_total_oov_only = 0.0;
    uint64_t corpus_tokens = 0;
    float total = 0.0;
    uint64_t oov = 0;
    model_->BeginSentenceWrite(&state);
    for(size_t i =0; i < words.size(); i++){
        VLOG(5) << "Get word: " << words[i];
        lm::WordIndex vocab = vocab_->Index(words[i]);
        VLOG(5) << "word index: " << vocab;
        ret = model_->BaseScore(&state, vocab, &out);
        if(vocab == vocab_->NotFound()){
            VLOG(5) << "out of vocab.";
            ++oov;
            corpus_total_oov_only += ret;
        }
        VLOG(5) << "get word freq: " << ret;
        total += ret;
        ++corpus_tokens;
        state = out;
    }
    // append EndSentence
    ret = model_->BaseScore(&state, vocab_->EndSentence(), &out);
    total += ret;
    VLOG(5) << "get eos freq: " << ret;
    VLOG(5) << "SentenceScoring total:" << total;
    return total;
}
```

## Test class

```
  GTEST_LOG_(INFO) << "init done.";
    std::vector< std::string> vec;
    vec.push_back("刘");
    vec.push_back("德");
    vec.push_back("华");
    float s = senscore.score(vec);
    GTEST_LOG_(INFO) << "score of '刘 德 华'" << s;
```

After run this testing code twice, I get different scores.
### Run 1
![screen shot 2018-03-10 at 6 36 01 pm](https://user-images.githubusercontent.com/3538629/37241312-41ce2660-2492-11e8-87f5-40ffce4e9d05.png)

### Run 2
![screen shot 2018-03-10 at 6 35 34 pm](https://user-images.githubusercontent.com/3538629/37241310-411c6f10-2492-11e8-9af3-7ec77b83a9c3.png)

So, something is wrong.

I can check the score of this sentence with python module. 

```
        model = kenlm.LanguageModel(LM)
        print('{0}-gram model'.format(model.order))
        sentence = '刘 德 华'
        print(sentence)
        print(model.score(sentence))
```
It works very well. 

So, can you give some clue to run with C++?

**Comment by Samurais** [comment]
After reading the codes more carefully, I get the following questions.

## in_state.words
after execution of ```model_->BeginSentenceWrite(&state)```, what value or word id(s) does ```in_state.words``` suppose to have?

**Comment by kpu** [comment]
Unused backoff fields are undefined.  But they also shouldn't be used because they're off the end of the n-gram length.  Can you make a minimal example: one function with 10-15 lines and hard-code the query you're running?

**Comment by Samurais** [comment]
I make a simple test class with your suggestions and it works well, the problem I mentioned does not happen. This code is run against your source codes, but in order to enable build with my project which is not using cmake, I have to make some changes in your source code, so, it is probably my changes that breaks something. It is not a bug for your project. Thanks for your reply.  

And this is my test class.
```
#include "lm/model.hh"
#include "lm/sizes.hh"
#include "util/file_piece.hh"
#include "util/usage.hh"

#include <algorithm>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <iomanip>
#include <limits>
#include <cmath>

#ifdef WIN32
#include "util/getopt.hh"
#else

#include <unistd.h>

#endif

using namespace std;

int main(int argc, char *argv[]) {
    std::cout << "chi model test ..." << endl;
    lm::ngram::Config config_;
    lm::base::Model *model_;
    const lm::base::Vocabulary *vocab_;


    // init
    config_.load_method = util::POPULATE_OR_READ;
    const char* file = "/kenlm/build/data/chi.arpa";
    model_ = lm::ngram::LoadVirtual(file, config_);
    vocab_ = &(model_->BaseVocabulary());

    std::cout << "init done." << endl;

    // sentence
    std::vector< std::string> words;
    words.push_back("刘");
    words.push_back("德");
    words.push_back("华");

    // scoring
    lm::ngram::Model::State state;
    lm::ngram::Model::State out;
    float ret;
    double corpus_total_oov_only = 0.0;
    uint64_t corpus_tokens = 0;
    float total = 0.0;
    uint64_t oov = 0;
    model_->BeginSentenceWrite(&state);
    for(size_t i =0; i < words.size(); i++) {
        lm::WordIndex vocab = vocab_->Index(words[i]);
        ret = model_->BaseScore(&state, vocab, &out);
        if(vocab == vocab_->NotFound()){
            ++oov;
            corpus_total_oov_only += ret;
        }
        total += ret;
        ++corpus_tokens;
        state = out;
    }
    ret = model_->BaseScore(&state, vocab_->EndSentence(), &out);
    total += ret;
    std::cout << "SentenceScoring total: " << total;

    return 0;
}
```

**Comment by Samurais** [comment]
Problem fixed, it is due to mem issue, just use a machine with more memory.
