### ISSUE TITLE
Kenlm lmplz Error

### ISSUE THREAD

**Issue by manishbansal-fk** [kpu/kenlm#136]
**Error :** 

=== 1/5 Counting and sorting n-grams ===
Reading /var/lib/ds/manish.bansal/hindi_lm_data_dedup.split
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:648 2:23553945600 3:44163649536
/var/lib/ds/manish.bansal/kenlm/lm/builder/adjust_counts.cc:42 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts() threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 1-grams with adjusted count 2 because we didn't observe any 1-grams with adjusted count 1; Is this small or artificial data?
Aborted

====== 
Sample Dataset : **Char level** hindi language LM (# of **unique** records : 183309)
ए ब ी ए न
ए ब ी ए
 ै ड
ए ड ् स
ए ड ् स
ए ड ्
ए म ् स
ए म
ए म ्
ए

Please help here.

**Comment by kpu** [comment]
`--discount_fallback`

**Comment by manishbansal-fk** [comment]
Tried already, its failing.
Command : kenlm/bin/lmplz --discount_fallback -o 3 -T tmp <hindi_lm_data_dedup.split >hindi_lm_data.arpa

Output : unrecognised option '--discount_fallback'

**Comment by kpu** [comment]
Then you're not using the latest version from this repo.  Check out a clean copy and compile.

**Comment by manishbansal-fk** [comment]
1) I was installing kenlm python wrapper using 
pip install https://github.com/kpu/kenlm/archive/master.zip [I think its **not available** now]

2) And I followed this article for kenlm training / compile, 
http://thegrandjanitor.com/2015/12/28/using-arpa-lm-with-python/
which has "git clone https://github.com/**vchahun**/kenlm.git"

3) Should I use below for training / compiling ?
http://kheafield.com/code/kenlm.tar.gz
with these steps 
 - cmake followed by "make -j 4"

[Not sure of difference between between point 2 & 3]

Please suggest relevant sources for both i) python wrapper ii) Train / Compile
