### ISSUE TITLE
kenlm interpolating lm

### ISSUE THREAD

**Issue by pdcoded** [kpu/kenlm#143]
@kpu There is no documentation on how you interpolate two lm. But looking at another issue, here is what you have suggested

lmplz -o 5 --intermediate set1.intermediate <set1.txt
lmplz -o 5 --intermediate set2.intermediate <set2.txt
lmplz -o 5 --intermediate set3.intermediate <set3.txt
interpolate -m set{1,2,3}.intermediate -t tuning.txt

Where set1,set2,set3 are the intermediate arpa files . What is the tuning txt model format. If there is an example to tune it , that would be great.

**Comment by kpu** [comment]
It's a preprocessed text file.  Customarily you use a few hundred lines of in-domain text on which to learn the weights.  These should be held out from training the component models.
