### ISSUE TITLE
RuntimeError: util\mmap.cc:234 in util::HugeMalloc threw ErrnoException because `!to.get()'.

### ISSUE THREAD

**Issue by karl-schelhammer-td** [kpu/kenlm#148]
I have successfully installed the kenlm module in windows, and for the most part it is working well.

One issue I have run into is a memory allocation error when attempting to load larger files.  So far I have tried loading the 3-gram.arpa (759M), 3-graom.pruned.3e-7.arpa(13M), and 3-gram.pruned.1e-7.arpa (34M) files from here: http://www.openslr.org/11/.

 The smaller two load fine but the larger throws an error on load:

```
import kenlm
model_path = 'arpa-files/3-gram.arpa'
model = kenlm.Model(model_path)
```

error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
kenlm.pyx in kenlm.Model.__init__ (python/kenlm.cpp:2519)()

RuntimeError: util\mmap.cc:234 in util::HugeMalloc threw ErrnoException because `!to.get()'.
Not enough space Failed to allocate 1813921056 bytes Byte: 58

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-10-5130e400a7e3> in <module>()
----> 1 model = kenlm.Model(model_path)

kenlm.pyx in kenlm.Model.__init__ (python/kenlm.cpp:2656)()

OSError: Cannot read model 'arpa-files/3-gram.arpa' (util\mmap.cc:234 in util::HugeMalloc threw ErrnoException becaus
```
Any suggestions on how to resolve would be appreciated.

**Comment by kpu** [comment]
Did you compile 32-bit or have less than 1.8 GB RAM free?

**Comment by karl-schelhammer-td** [comment]
I installed the python package via pip install `https://github.com/kpu/kenlm/archive/master.zip`.  I'm not sure if I installed 32 bit nor how to check.

I am on a 16 GB machine - currently 8GB is on standby and 0.5GB is free.  I ran Process Hacker to clear the standby, leaving over 8GB free.  I then ran the model load again and it failed again with the same error.

**Comment by kpu** [comment]
I think you've compiled 32-bit.  Don't know how to change windows to 64-bit.  https://stackoverflow.com/questions/27488163/python-3-4-compile-cython-module-for-64-bit-windows ?

**Comment by karl-schelhammer-td** [comment]
I looked into my python environment in a bit more detail and sure enough it was 32-bit.  I activated a 64-bit environment, installed the module and everything is working again.

I think it's fine to close this issue.
