### ISSUE TITLE
Issue while trying to create binary file

### ISSUE THREAD

**Issue by praffulsi** [kpu/kenlm#149]
HI, 

I ran into this problem below while trying to create binary file. Can you please tell what is going wrong?

Prafful’s MacBook Pro:~ naveen$ /Users/naveen/Downloads/kenlm/build/bin/build_binary -T -s /Users/naveen/Downloads/kenlm/build/words.arpa lm.binary
Reading /Users/naveen/Downloads/kenlm/build/words.arpa
----5—10—15—20—25—30—35—40—45—50—55—60—65—70—75—80—85—90—95–100

/Users/naveen/Downloads/kenlm/lm/vocab.cc:305 in void lm::ngram::MissingSentenceMarker(const lm::ngram::Config &, const char *) threw SpecialWordMissingException.
The ARPA file is missing and the model is configured to reject these models. Run build_binary -s to disable this check. Byte: 191298
ERROR

**Comment by kpu** [comment]
Is there anything unclear about the error message?

**Comment by praffulsi** [comment]
Yes, why am I getting this error? I passed a normal words.arpa file for
converting to binary.

"vocab.cc:305 in void lm::ngram::MissingSentenceMarker(const
lm::ngram::Config &, const char *) threw SpecialWordMissingException.

The ARPA file is missing and the model is configured to reject these
models"

**Comment by kpu** [comment]
Take care to read the message and to escape any HTML-like characters that Github is stripping out. 

Use the preview tab to make sure things are being reported accurately. It says "The ARPA file is missing &lt;s&gt;" or "The ARPA file is missing &lt;/s&gt;".

**Comment by praffulsi** [comment]
I am really sorry but I didn't understand the first line of your reply
clearly.

**Comment by kpu** [comment]
You might want to learn about begin and end of sentence tags at https://www.researchgate.net/post/Whats_the_real_need_for_an_end-symbol_in_n-gram_models
