### ISSUE TITLE
Kneyser_Ney Estimation for Characters

### ISSUE THREAD

**Issue by numericlee** [kpu/kenlm#151]
Can KenLM or Kneyser-Ney Estimation be adapted from modelling language to characters?

My application involves the distribution of characters (say, the digits of a telephone number or street addresses) rather than words which I would like to train .

I have a probability vector for each position based on  LeNet5 and an incomplete corpus of valid phone numbers.  I would like to model based on sequences of several characters rather than several words.

**Comment by kpu** [comment]
Yes. Put spaces between letters, run lmplz with `--discount_fallback`.
