### ISSUE TITLE
KLM Estimation

### ISSUE THREAD

**Issue by numericlee** [kpu/kenlm#152]
Thank you for your prompt and helpful response on   #150 
I modified the tokenizer as you suggested. Scores still  don’t make appear to make sense. Am I doing something wrong here ?

I tried both a trigram and 5-gram with similar results

Also,  is there a metric to make useful comparisons of phrases of different length.

**_Trigram model using KenLM, Brown Corpus, lowercase tokenizer_**
Corpus:	       http://www.sls.hawaii.edu/bley-vroman/brown_nolines.txt
Envt:                Python 2.7.12  on linux2

# **Results**

```
    import kenlm
    model = kenlm.LanguageModel('brown10e.klm')
```

phrase | Model.score()
-- | --
'the jury also commented on the fulton ordinary court   which has been under fire for its practices' | -28.80450439453125
 'fulton county courthouse' | -15.42793083190918
'hola, estoy bien. dldldldldl www dndldl  gracias' | -15.239280700683594
'in the beginning was the word' | -15.173033714294434
"plainly reasonable" | -12.628071784973145
'the jury also' | -8.662643432617188
"unreasx plainz" | -5.3799357414245605

# **Tokenizer/Process:**
 nltk_process10e.py

```
import  re, sys, codecs, nltk
from nltk.tokenize.moses import MosesTokenizer

wrapper = codecs.getreader(encoding ='utf-8')
reader =   wrapper(sys.stdin)
string1 = reader.readlines() 

for line in string1:
    string2 =line.encode("ascii", errors="ignore").lower()
    string3 = re.sub("\s+",  " ", string2) 
    m= MosesTokenizer()
    tokens = m.tokenize(string3)

    def retain(x):
        if x[0]=="&":
            return "_"
        else:
            return x
    tokens2 = [retain(x) for x in tokens]

    if tokens2:
        sent = ' '.join(tokens2)
        sent =sent.replace("_ ","").replace(" _","")
        sent =sent.replace("# ","").replace(" #","")
        #sent =sent.replace(" , "," ")
        sent =sent.replace(" ^ "," ")

        print (sent)


```
# **Compilation Log**

 (FM27) Smith@Ajax:~$ cat  FMM/brown_nolines.txt | python nltk_process10e.py |  ./kenlm/bin/lmplz -o 3 > 

FMM/brown10e.arpa
=== 1/5 Counting and sorting n-grams ===
File stdin isn't normal.  Using slower read() instead of mmap().  No progress bar.
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:695916 2:4756443136 3:8918330368
Statistics:
1 57993 D1=0.62421 D2=1.04433 D3+=1.41898
2 460690 D1=0.790594 D2=1.1174 D3+=1.39255
3 888745 D1=0.8911 D2=1.21584 D3+=1.42926
<Memory estimates omitted>

=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:695916 2:7371040 3:17774900
=== 4/5 Calculating and writing order-interpolated probabilities ===
=== 5/5 Writing ARPA model ===
Name:lmplz      VmPeak:0 kB     VmRSS:30016 kB  RSSMax:0 kB     user:0  sys:0   CPU:0   real:28.8623

(FM27) Smith@Ajax:~$ ./kenlm/bin/build_binary FMM/brown10e.arpa brown10e.klm
Reading FMM/brown10e.arpa
SUCCESS

**Comment by kpu** [comment]
For an introduction on n-gram language modeling, see https://web.stanford.edu/class/cs124/lec/languagemodeling.pdf

**Comment by numericlee** [comment]
@kpu  that helps.
