### ISSUE TITLE
discount_fallback usage

### ISSUE THREAD

**Issue by numericlee** [kpu/kenlm#153]
for sequential labelling of surnames - see below

**Comment by numericlee** [comment]
Following your suggestion for treating each character as a gram

cat input.csv | python process.py |  ./kenlm/bin/lmplz -o 3 discount_fallback > output.arpa

The data coming out pf process.py and  into lmplz is of the following form:
j o h n s o n
s m i t h
...
d a l t o n

The vocabulary is restricted to the 26 lowercase letters

For now I have avoided duplication (though in the future I would like to reflect the relative frequency of  smith and dalton)

I assume lmplz is unhappy because of the restricted vocabulary. How can I fix this

=== 1/5 Counting and sorting n-grams ===
File stdin isn't normal.  Using slower read() instead of mmap().  No progress bar.
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:348 2:4756684800 3:8918784000

Ajax/kenlm/lm/builder/adjust_counts.cc:42 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts() threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 1-grams with adjusted count 2 because we didn't observe any 1-grams with adjusted count 1; Is this small or artificial data?

Thanks

**Comment by kpu** [comment]
Uh `--discount_fallback` != `discount_fallback`
