### ISSUE TITLE
Boost headers not found

### ISSUE THREAD

**Issue by mojesty** [kpu/kenlm#158]
Hi, I installed boost via `sudo ./bootstrap.h` and `sudo ./b2`
However, when I run `make ..` command from `kenlm_dir/build`,  I got the following:
```
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_thread

  Some (but not all) of the required Boost libraries were found.  You may

```

I checker `/usr/include` and found `boost` dir there with `thread.hpp` and thread directory, so I assume that the installation itself is OK

In the error log made by the cmake I found
 ```
bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/$
/usr/bin/ld: cannot find -lpthreads
```
So i completely don't understand what's going on.
Could you help?

**Comment by kpu** [comment]
Update to the code from this repo.  Also, where did you get the ancient copy from?

**Comment by mojesty** [comment]
I used a download link: http://kheafield.com/code/kenlm.tar.gz
"Normally it works but i can not gurantee it" heavily discouraged me from using the master version.
Now it installed successfully even without eigen3, hope that will work well

**Comment by kpu** [comment]
That's embarrassing.  I have updated it.  

eigen3 is only for interpolation which just about nobody uses.
