### ISSUE TITLE
What does full_score return？

### ISSUE THREAD

**Issue by orangetwo** [kpu/kenlm#165]
Thank you very much, I am using the toolkit you developed. But now I am a bit confused, I looked at the kenlm/python/kenlm.pyx file and found that the score function returned is a joint probability (if  <s and <\s> are ignored). I understand this right?

Is the return value of the perplexity function essentially the same as the score? (return 10.0**(-self.score(sentence) / words))

There is also a question, is the full_scores function return a conditional probability? Like this p(wi| wi-1, ...wi-j)?

I am sorry that my English is not good.

thanks again。

**Comment by kpu** [comment]
The score function returns the log10 probability of a sentence.  Perplexity can be computed from this, as documented in the perplexity function.  

You can get individual conditional log10 probabilities from full_scores in a list.  Or read the implementation of full_scores to see the low-level functions for conditional probability.

**Comment by orangetwo** [comment]
In the  kenlm/lm/test.arpa file, then \2-grams:
-0.09132547	a little	-0.69897
this line denote log10 (little | a) = -0.09132547  
or log10 (a, little) = -0.09132547 ？
Which understanding is correct?

thank you.
