### ISSUE TITLE
unable to read apra file of 76gb

### ISSUE THREAD

**Issue by saibharani** [kpu/kenlm#169]
I have created an apra file using common crawl data and its size is around 76gb. When I try to convert it to binary it failed with `!to.get()' error. I even tried to increase the swap memory size then it started reading but struck at around 20%. my system is 64bit with 16gb ram and 115gb swap memory. I am unable to use the arpa file directly too. It also ends up with the same problem as above.
can you please tell me how to use such large arpa files.

**Comment by kpu** [comment]
Read https://kheafield.com/code/kenlm/structures/ .

**Comment by saibharani** [comment]
I followed it as specified in the link. the least possible option is 14gb with quantization. I tried it but it is not making a progress more than 38%. Is there no way I can use the swap to compensate the low RAM. I made sure nearly 15gb ram was available for the work.
