### ISSUE TITLE
How to generate sentences in Python?

### ISSUE THREAD

**Issue by djshowtime** [kpu/kenlm#170]
I only found [./generate.sh](https://github.com/kpu/kenlm/blob/master/lm/common/test_data/generate.sh), which can generate sentences.

Does it support generating in Python? Or I need to retrieve the prob of words from arpa file and then generate~~~

**Comment by kpu** [comment]
The generate.sh you linked to generates test data, not sentences from a model.  

KenLM implements a reverse trie data structure, in which the last word is looked up first.  It wasn't designed to efficiently provide a distribution over all successor words.  A forward trie is better for this.  

You can generate a State object then do a for loop over all successors, but it will be slow.  Note that vocabulary ids are consecutive.
