### ISSUE TITLE
Access Vocabulary of a language model?

### ISSUE THREAD

**Issue by SachithSriRam** [kpu/kenlm#176]
I have build a language model (.arpa format). I am trying to access it's vocabulary to constrain other models while comparing perplexity.
I couldn't find any straightforward way to access the vocabulary.
Can we take the list of unigrams (+OOV) as the vocabulary of the model (if we don't set any vocab_estimate or vocab_pad while training)?

**Comment by kpu** [comment]
You can do that even with `--vocab_estimate` (which has no impact on the output) and `--vocab_pad`.
