### ISSUE TITLE
Perplexity calculation

### ISSUE THREAD

**Issue by seriouscoder123** [kpu/kenlm#181]
In Python module perplexity is calculated like this:

 `       words = len(as_str(sentence).split()) + 1 # For </s>`
 `      return 10.0**(-self.score(sentence) / words)`

Since `self.score(sentence)` adds both `<s>` and `</s>`, I was thinking `words` needs to be increased by 1. 

`words = len(as_str(sentence).split()) + 2 # For <s> and </s>`

Is my understanding correct?

**Comment by kpu** [comment]
No, because <s> is the big bang.  It happened and everything is conditioned on that.
