### ISSUE TITLE
Cannot allocate memory Failed to allocate xxx bytes

### ISSUE THREAD

**Issue by tiefenauer** [kpu/kenlm#185]
I am trying to train a German 4-gram LM on a Wikipedia dump that was preprocessed extracting raw text (sentences) with NLTK. During estimation I get this error:

```
bin/lmplz -o 4 -T /home/daniel/tmp/ --skip_symbols -S 40% <wiki_de.txt.bz2 | bin/build_binary /dev/stdin wiki_de_4_gram.klm
File /dev/stdin isn't normal.  Using slower read() instead of mmap().  No progress bar.
=== 1/5 Counting and sorting n-grams ===
Reading /home/daniel/ip9/lm_data/wiki_de/wiki_de.txt.bz2
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
Warning: <unk> appears in the input.  All instances of <s>, </s>, and <unk> will be interpreted as whitespace.
****************************************************************************************************
Unigram tokens 682508705 types 8426416
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:101116992 2:429356768 3:805043968 4:1288070400
Statistics:
1 8426416 D1=0.686128 D2=1.03097 D3+=1.34892
2 107683108 D1=0.785954 D2=1.10665 D3+=1.35669
3 298762827 D1=0.865376 D2=1.16385 D3+=1.34682
4 445261051 D1=0.88679 D2=1.26159 D3+=1.36648
Memory estimate for binary LM:
type       MB
probing 17155 assuming -p 1.5
probing 19513 assuming -r models -p 1.5
trie     8732 without quantization
trie     5234 assuming -q 8 -b 8 quantization 
trie     7711 assuming -a 22 array pointer compression
trie     4213 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:101116992 2:543584576 3:1019221120 4:1630753792
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 4/5 Calculating and writing order-interpolated probabilities ===
Chain sizes: 1:64805060 2:172813488 3:324025312 4:518440480
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 5/5 Writing ARPA model ===
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
----/home/daniel/kenlm/util/mmap.cc:234 in void util::HugeMalloc(std::size_t, bool, util::scoped_memory&) threw ErrnoException because `!to.get()'.
Cannot allocate memory Failed to allocate 17836812424 bytes Byte: 78
ERROR
```
I already found issue #71 with the same problem and read that it might be related to insufficient free space on the hard disk. However, both the temp and the target directory are on the same hard disk with >70G free space and the memory estimate is around 17G.

I trained a 2-gram model on the same data and all parameters identical (except `-o` of course), that worked. The size of the binary file produced is then 2.3G.

I am using Ubuntu 18.04 LTS on an i7 laptop with 8GB RAM and a very fast SSD.

Any idea what could cause this problem?

UPDATE: After a reboot I was at least able to write the ARPA file, which is ~37G. I moved this file to an USB stick to free some space on the SSD. I tried to build the binary from there, but it gives me the same error message again.

**Comment by kpu** [comment]
RAM != disk.  In this case it is saying that it cannot allocate memory.  Use a lower -S argument.

**Comment by tiefenauer** [comment]
That did not work either. I tried the following:
```
cat wiki_de_4_gram_500k.arpa | build_binary -w mmap -S 10% -T /home/daniel/tmp /dev/stdin wiki_de_4_gram_500k.klm 
```
Even going down to 1% did not not help. Same error, immediately after running `build_binary`. I also tried the `-w mmap` flag just to see. This does not abort immediately, but seems incredibly slow.

**Comment by tiefenauer** [comment]
Yes, I tried this, but I'd rather get the build done with `-w after` because it's faster and shows a progress bar. I limited the vocabulary to 500k words for performance, but those words make up for more than 96% of the corpus. I'd rather not go below this limit since German texts tend to use a bigger vocabulary and there are also a lot of derivate words (flexions, cases) that I don't/can't lemmatize or stem because that is not how humans speak/write.

I am actually not sure whether a 4-gram model can be trained on a normal machine like mine, even with KenLM, but the 2-gram model built in 2-3h. Any idea how this time scales for a 4-gram model.

**Comment by kpu** [comment]
Also, the trie model combines much better with `-w mmap` since it does n sequential streams.

**Comment by tiefenauer** [comment]
Building the trie model worked and was indeed much faster. Itgave me an error yesterday, dunno what changed. I will use this although it might be a bit slower than the model using hash arrays. Thanks.

**Comment by qwtao** [comment]
I came up with the same problem as the title describes, and the `S` argument with a value of `40%` fixed my problem. Thx all.

**Comment by kite99520** [comment]
I was also confused about this, add ` -s 40% ` and it works. Thanks!
