### ISSUE TITLE
can not install in mac 10.14

### ISSUE THREAD

**Issue by axboris** [kpu/kenlm#186]
Collecting kenlm
  Using cached https://files.pythonhosted.org/packages/57/54/0cc492b8d7aceb17a9164c6e6b9c9afc2c73706bb39324e8f6fa02f7134a/kenlm-0.tar.gz
Building wheels for collected packages: kenlm
  Running setup.py bdist_wheel for kenlm: started
  Running setup.py bdist_wheel for kenlm: finished with status 'error'
  Complete output from command /Users/boriswang/py365/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pycharm-packaging/kenlm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pip-wheel-uqi_lub5 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'kenlm' extension
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/util
  creating build/temp.macosx-10.6-intel-3.6/lm
  creating build/temp.macosx-10.6-intel-3.6/util/double-conversion
  creating build/temp.macosx-10.6-intel-3.6/python
  gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -I/usr/local/opt/openssl/include -arch x86_64 -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c util/pool.cc -o build/temp.macosx-10.6-intel-3.6/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from util/pool.cc:1:
  ./util/pool.hh:4:10: fatal error: 'cassert' file not found
  #include <cassert>
           ^~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for kenlm
Failed to build kenlm
Installing collected packages: kenlm
  Running setup.py install for kenlm: started
    Running setup.py install for kenlm: finished with status 'error'
    Complete output from command /Users/boriswang/py365/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pycharm-packaging/kenlm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pip-record-s47pugkh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/boriswang/py365/bin/../include/site/python3.6/kenlm:
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/util
    creating build/temp.macosx-10.6-intel-3.6/lm
    creating build/temp.macosx-10.6-intel-3.6/util/double-conversion
    creating build/temp.macosx-10.6-intel-3.6/python
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -I/usr/local/opt/openssl/include -arch x86_64 -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c util/pool.cc -o build/temp.macosx-10.6-intel-3.6/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from util/pool.cc:1:
    ./util/pool.hh:4:10: fatal error: 'cassert' file not found
    #include <cassert>
             ^~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

  Failed building wheel for kenlm
Command "/Users/boriswang/py365/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pycharm-packaging/kenlm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pip-record-s47pugkh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/boriswang/py365/bin/../include/site/python3.6/kenlm" failed with error code 1 in /private/var/folders/kj/v5vwsdpj4svfzy83vtk_njpw0000gn/T/pycharm-packaging/kenlm/

**Comment by melanietosik** [comment]
I have the same issue, `macOS Mojave (10.14)` as well. Any advice?

**Comment by kpu** [comment]
Try now?

**Comment by kpu** [comment]
I hate Apple.  How about now?

**Comment by melanietosik** [comment]
Haha I'm sorry, it works now! Thank you so much, I appreciate it!

**Comment by xikunlun001** [comment]
@kpu 
still not working

**Comment by kpu** [comment]
@xikunlun001 it looks like your c++ setup isn't fully installed if you're missing cassert.

**Comment by ShuaiqunPan** [comment]
It works now.

**Comment by kFoodie** [comment]
how dou you do this??

**Comment by kFoodie** [comment]
I have the same problem, but I can't solve it..

**Comment by kpu** [comment]
Please before posting here, create a simple C++ file.  Let's call it `foo.cc`
```
#include <cassert>
int main() {
   assert(true);
}
```
Then compile
```
clang foo.cc
```
That should print nothing.  If it prints something, your C++ environment is broken and it's not a bug in KenLM.  Since I have a policy of only buying reasonably priced computers with at least three mouse buttons, I cannot help you with setting up C++ on OS X.  

@kFoodie Post build log.

**Comment by kFoodie** [comment]
> Please before posting here, create a simple C++ file. Let's call it `foo.cc`
> 
> ```
> #include <cassert>
> int main() {
>    assert(true);
> }
> ```
> Then compile
> 
> ```
> clang foo.cc
> ```
> That should print nothing. If it prints something, your C++ environment is broken and it's not a bug in KenLM. Since I have a policy of only buying reasonably priced computers with at least three mouse buttons, I cannot help you with setting up C++ on OS X.
> 
> @kFoodie Post build log.

My c++ environment doesn't have any problem, it print nothing. But I still can't install kenLM by `pip install https://github.com/kpu/kenlm/archive/master.zip` directly.. Thanks for your help.

**Comment by rzhang-asapp** [comment]
`CFLAGS=-stdlib=libc++ pip install kenlm`
This one works for me

**Comment by NikosEfthias** [comment]
well this still seems to be an issue
