### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sevilaybayatli** [kpu/kenlm#188]
-- Configuring incomplete, errors occurred!
See also "/root/Normalization/kenlm/build/CMakeFiles/CMakeOutput.log".
See also "/root/Normalization/kenlm/build/CMakeFiles/CMakeError.log".

**Comment by kpu** [comment]
Attach the full log.

**Comment by sevilaybayatli** [comment]
root@ip-172-31-28-90:~/Normalization/kenlm/build# cmake ..
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (find_package)


CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (find_package)


CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (find_package)


CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:66 (find_package)


CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:66 (find_package)


-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing: LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
CMake Warning at lm/interpolate/CMakeLists.txt:65 (message):
  Not building interpolation.  Eigen3 was not found.


-- To install Eigen3 in your home directory, copy paste this:
export EIGEN3_ROOT=$HOME/eigen-eigen-07105f7124f9
(cd $HOME; wget -O - https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 |tar xj)
rm CMakeCache.txt

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/double-conversion
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/util/stream
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/common
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/builder
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/filter
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate
   used as include directory in directory /root/Normalization/kenlm/lm/interpolate

-- Configuring incomplete, errors occurred!
See also "/root/Normalization/kenlm/build/CMakeFiles/CMakeOutput.log".
See also "/root/Normalization/kenlm/build/CMakeFiles/CMakeError.log".

**Comment by ttambe** [comment]
Hey guys, I'm getting the same error after running "cmake ..". Any solution here?

**Comment by sevilaybayatli** [comment]
I think you missing some libraries like libboost, libicu,
libgoogle-perftools and zlib.  For me after install all missing libraries
it worked.

**Comment by ttambe** [comment]
Ok, thank you! I'll look into that

**Comment by kpu** [comment]
https://kheafield.com/code/kenlm/dependencies/
