### ISSUE TITLE
Estimating error

### ISSUE THREAD

**Issue by sevilaybayatli** [kpu/kenlm#189]
Hello,
I have tried both command for estimation and in both of them not worked, please need help to fix it as soon as possible because I have deadline for my project.

/kenlm/build$ bin/lmplz -o 5 <wiki.txt >text.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /home/ubuntu/Normalization/kenlm/build/wiki.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 52187060 types 3207944
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:38495328 2:2629386752 3:4930100224 4:7888160256 5:11503567872
Statistics:
1 3207944 D1=0.745905 D2=1.0353 D3+=1.27681
2 23265718 D1=0.846169 D2=1.13695 D3+=1.29919
3 39361841 D1=0.929966 D2=1.25787 D3+=1.35771
4 43803518 D1=0.972149 D2=1.40271 D3+=1.46654
5 43939553 D1=0.958173 D2=1.57706 D3+=1.57683
Memory estimate for binary LM:
type      MB
probing 3269 assuming -p 1.5
probing 3891 assuming -r models -p 1.5
trie    1759 without quantization
trie    1042 assuming -q 8 -b 8 quantization 
trie    1520 assuming -a 22 array pointer compression
trie     803 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:38495328 2:372251488 3:787236820 4:1051284432 5:1230307484
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Last input should have been poison.
Aborted (core dumped)

/kenlm/build$ bin/lmplz -o 5 -S 80% -T /tmp <wiki.txt >text.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /home/ubuntu/Normalization/kenlm/build/wiki.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 52187060 types 3207944
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:38495328 2:2629386752 3:4930100224 4:7888160256 5:11503567872
Statistics:
1 3207944 D1=0.745905 D2=1.0353 D3+=1.27681
2 23265718 D1=0.846169 D2=1.13695 D3+=1.29919
3 39361841 D1=0.929966 D2=1.25787 D3+=1.35771
4 43803518 D1=0.972149 D2=1.40271 D3+=1.46654
5 43939553 D1=0.958173 D2=1.57706 D3+=1.57683
Memory estimate for binary LM:
type      MB
probing 3269 assuming -p 1.5
probing 3891 assuming -r models -p 1.5
trie    1759 without quantization
trie    1042 assuming -q 8 -b 8 quantization 
trie    1520 assuming -a 22 array pointer compression
trie     803 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:38495328 2:372251488 3:787236820 4:1051284432 5:1230307484
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Last input should have been poison.
Aborted (core dumped)

**Comment by kpu** [comment]
This looks like it ran out of disk space.  Is this the latest version?  The master version should have given you a more specific error.

**Comment by sevilaybayatli** [comment]
Yes I follow  the instructions  in your site now and download and setup
everything from there  and I am using server my RAM 64 GB

**Comment by kpu** [comment]
RAM != disk.

**Comment by sevilaybayatli** [comment]
What can I do with disk how should I do for fix this problem

**Comment by kpu** [comment]
Point -T to a drive with a lot of disk.

**Comment by sevilaybayatli** [comment]
please can you give me the whole command to for using -T because I already
use this one

/kenlm/build$ bin/lmplz -o 5 -S 80% -T /tmp <wiki.txt >text.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /home/ubuntu/Normalization/kenlm/build/wiki.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 52187060 types 3207944
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:38495328 2:2629386752 3:4930100224 4:7888160256 5:11503567872
Statistics:
1 3207944 D1=0.745905 D2=1.0353 D3+=1.27681
2 23265718 D1=0.846169 D2=1.13695 D3+=1.29919
3 39361841 D1=0.929966 D2=1.25787 D3+=1.35771
4 43803518 D1=0.972149 D2=1.40271 D3+=1.46654
5 43939553 D1=0.958173 D2=1.57706 D3+=1.57683
Memory estimate for binary LM:
type      MB
probing 3269 assuming -p 1.5
probing 3891 assuming -r models -p 1.5
trie    1759 without quantization
trie    1042 assuming -q 8 -b 8 quantization
trie    1520 assuming -a 22 array pointer compression
trie     803 assuming -a 22 -q 8 -b 8 array pointer compression and
quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:38495328 2:372251488 3:787236820 4:1051284432 5:1230307484
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Last
input should have been poison.
Aborted (core dumped)

**Comment by sevilaybayatli** [comment]
I dont know how can I use this

Point -T to a drive with a lot of disk.

I already used it as /kenlm/build$ bin/lmplz -o 5 -S 80% -T /tmp <wiki.txt
>text.arpa

could you tell me how to use it?
