### ISSUE TITLE
Clarifying procedure to generate a binary KenLM language model

### ISSUE THREAD

**Issue by ttambe** [kpu/kenlm#190]
Hi,

I want to generate a binary KenLM language model so that I can plug it into my decoder for improving inference. I'm still confused about the proper procedure to do so. Here is my understanding of this procedure, please correct me where I'm wrong:

1) First, compile with the commands:
mkdir -p build
cd build
cmake ..
make -j 4

2) Then, build for example a 3-gram LM with
bin/lmplz -o 3 <vocab.txt > 3glm.arpa

3) And then generate the binary LM with:
~/kenlm/build/bin/build_binary -T -s 3glm.arpa lm.binary

Is the correct procedure? Thank you!

**Comment by kpu** [comment]
`-T` is meant to be used with an argument specifying where to put temporary files.  It's also really only used for the trie format, which is not the default.  
`-s` isn't necessary for models coming out of `lmplz`
So e.g. `build_binary -T /bigdisk 3glm.arpa lm.binary` but otherwise fine

**Comment by ttambe** [comment]
Thanks a lot!
