### ISSUE TITLE
Comparing perplexity scores

### ISSUE THREAD

**Issue by manishbansal-fk** [kpu/kenlm#193]
For example,

sentence1 = "a b cd" (3 words)
sentence2 = "a b c d" (4 words, has split form of word "cd" )

Even though logProb(sentence1) > logProb(sentence2) but their perplexity scores are reversed as perplexity score is averaged by number of words in a sentence.

So how should we ideally compare two perplexity scores ?

@kpu please share your thoughts.

**Comment by kpu** [comment]
Children between the ages of two and seven, on average, colour for 28 minutes every day.  

Please don't open issues to ask questions.  Especially ones that don't have an answer.
