### ISSUE TITLE
input file format - sentence conditional independence? 

### ISSUE THREAD

**Issue by PCerles** [kpu/kenlm#196]
Hi, I'm building a language model with punctuation and wondering why we split input sentences on each new line. Doesn't this assume that sentences are independent? E.g., when trying to model dialogue between two speakers:

Where are you from? I am from England. 

We would probably want to model the 5-gram probability of "you from? I am from" in a general speech transcription model, right?

If we split on each sentence, we would have

Where are you from?
I am from England

as separate examples.
 
Maybe we only assume that period-separated sentences have conditional independence? Or I might be misunderstanding how LM construction works. Not sure. Thanks!

**Comment by kpu** [comment]
For better or worse, it does assume sentences are independent.  You can put everything on one line to do cross-sentence n-grams; I think the code was written carefully enough to allow for this case without loading the entire line in RAM.  
CMU-Cambridge did some experiments long ago with n-grams that continue across sentence boundaries.  
Though to be honest much of the cross-sentence context you're looking for won't be captured in a 5-word window anyway, and it would probably be better to use a neural model for this.

**Comment by PCerles** [comment]
Thanks for the quick response (and the great library). You're right -- as soon as I typed out my example, I realized most of the context is probably lost even with 5-grams. I can probably write it myself pretty quickly, but do you know a quick perl/bash script for replacing all unigrams below a certain count with <unk>?

**Comment by kpu** [comment]
To your second question, unking rare words is a bad idea with n-gram language models because it breaks smoothing assumptions.  So no I don't have such a script.
