### ISSUE TITLE
can not install in mac 10.14..

### ISSUE THREAD

**Issue by kFoodie** [kpu/kenlm#197]
pip install https://github.com/kpu/kenlm/archive/master.zip
Collecting https://github.com/kpu/kenlm/archive/master.zip
  Downloading https://github.com/kpu/kenlm/archive/master.zip
     / 3.5MB 2.1MB/s
Building wheels for collected packages: kenlm
  Running setup.py bdist_wheel for kenlm ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-req-build-eqdf1jmi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-wheel-1oalngmj --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'kenlm' extension
  creating build
  creating build/temp.macosx-10.6-intel-3.6
  creating build/temp.macosx-10.6-intel-3.6/util
  creating build/temp.macosx-10.6-intel-3.6/lm
  creating build/temp.macosx-10.6-intel-3.6/util/double-conversion
  creating build/temp.macosx-10.6-intel-3.6/python
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c util/pool.cc -o build/temp.macosx-10.6-intel-3.6/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -stdlib=libc++ -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  error: command '/usr/bin/clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for kenlm
  Running setup.py clean for kenlm
Failed to build kenlm
Installing collected packages: kenlm
  Running setup.py install for kenlm ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-req-build-eqdf1jmi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-record-essezxos/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/util
    creating build/temp.macosx-10.6-intel-3.6/lm
    creating build/temp.macosx-10.6-intel-3.6/util/double-conversion
    creating build/temp.macosx-10.6-intel-3.6/python
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I. -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c util/pool.cc -o build/temp.macosx-10.6-intel-3.6/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11 -stdlib=libc++ -DHAVE_ZLIB -DHAVE_BZLIB -DHAVE_XZLIB
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-req-build-eqdf1jmi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-record-essezxos/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-req-build-eqdf1jmi/

**Comment by kFoodie** [comment]
export MACOSX_DEPLOYMENT_TARGET=10.14.2
Swifers-MacBook-Pro:~ zhengguokai$ pip install https://github.com/kpu/kenlm/archive/master.zip
Collecting https://github.com/kpu/kenlm/archive/master.zip
  Downloading https://github.com/kpu/kenlm/archive/master.zip
     \ 3.5MB 830kB/s
Building wheels for collected packages: kenlm
  Running setup.py bdist_wheel for kenlm ... done
  Stored in directory: /private/var/folders/xs/n_q55hhs49s31m1gvhnrf5z00000gn/T/pip-ephem-wheel-cache-efky4shk/wheels/2d/32/73/e3093c9d11dc8abf79c156a4db1a1c5631428059d4f9ff2cba
Successfully built kenlm
Installing collected packages: kenlm
Successfully installed kenlm-0.0.0

**Comment by kpu** [comment]
Glad you got it to work.  I've tried to integrate what you did.  Does master work now?

**Comment by kFoodie** [comment]
Oh, I am just a student...

**Comment by kpu** [comment]
Borrowed a mac from another student.  Fixed.
