### ISSUE TITLE
Binary file not getting generated after ARPA

### ISSUE THREAD

**Issue by sgangs** [kpu/kenlm#199]
I have created the ARPA file from the latest Wiki dump. The size of the Wiki dump is about 13.1 GB (after all text processing) and the ARPA file is about 68GB. (4-gram). Now, as I try creating the "binary" file, the same is starting, running upto about 10% and then hanging. I'm using "-T" option to denote to a 210 GB drive location (in my \home\user). There's no error being shown. The Binary file is getting created without anything inside (0 byte). Could you suggest what's the issue.

I have both tried:

1. ../kenlm/build/bin/lmplz -o 4 -T /home/sayantan  <complete_wiki.txt >lm_revised.arpa | ../kenlm/build/bin/build_binary /dev/stdin lm_wiki.binary

And

2. ../kenlm/build/bin/lmplz -o 4 -T /home/sayantan  <complete_wiki.txt >lm_revised.arpa
 ../kenlm/build/bin/build_binary -T /home/sayantan lm.arpa lm.binary

While the first one stopped silently while for the second one, it shows reading lm.arpa and then stops at 10%.

Could you suggest what's the issue?

**Comment by kpu** [comment]
Most likely you ran out of RAM and the out of memory killer came by. You'll see it by looking in `dmesg`.  Choose a smaller data structure: https://kheafield.com/code/kenlm/structures/

**Comment by sgangs** [comment]
Thanks a lot. Just shut down the computer to give it a "rest" :). I saw my dmesh anfd the only probably dmesg which could be slightly related would be:

Jan 01 19:18:52 sayantan-Nitro kernel: perf: interrupt took too long (2502 > 2500), lowering kernel.perf_event_max_sample_rate to 79750


There's been no other related outputs. Some bluetooth and wifi messages over the last 6-7 hours. 

Regarding RAM, I've a 16GB RAM and its only a 68GB file. Not sure how the arpa to binary process work, but as you said, if it were for RAM, there should've been some killer. But none were there.

Finally, for the data structure, do you then suggest I go for trie structure with default (dynamic) quantization?

**Comment by sgangs** [comment]
> Most likely you ran out of RAM and the out of memory killer came by. You'll see it by looking in `dmesg`. Choose a smaller data structure: https://kheafield.com/code/kenlm/structures/

Thanks a lot. Just shut down the computer to give it a "rest" :). I saw my dmesh anfd the only probably dmesg which could be slightly related would be:

Jan 01 19:18:52 sayantan-Nitro kernel: perf: interrupt took too long (2502 > 2500), lowering kernel.perf_event_max_sample_rate to 79750

There's been no other related outputs. Some bluetooth and wifi messages over the last 6-7 hours.

What I'm thinking is, is the ARPA file alright? Like there has been no error message whatsoever; hence I should not doubt the generation of ARPA; still is there any command to check the integrity of the generated ARPA file?

Regarding RAM, I've a 16GB RAM and ARPA is a 68GB file. Not sure how the arpa to binary process work, but as you said, if it were for RAM, there should've been some killer initiated. But none were there, not in dmesg atleast.

Finally, for the data structure, do you then suggest I go for trie structure with default (dynamic) quantization?
