### ISSUE TITLE
ARPA to BInary faails, follow-up (Most likely you ran out of RAM)

### ISSUE THREAD

**Issue by sgangs** [kpu/kenlm#200]
Followup to 
https://github.com/kpu/kenlm/issues/199

_Originally posted by @kpu in https://github.com/kpu/kenlm/issues/199#issuecomment-450742110_

Thanks a lot. Just shut down the computer to give it a "rest" :). I saw my dmesh anfd the only probably dmesg which could be slightly related would be:

Jan 01 19:18:52 sayantan-Nitro kernel: perf: interrupt took too long (2502 > 2500), lowering kernel.perf_event_max_sample_rate to 79750

There's been no other related outputs. Some bluetooth and wifi messages over the last 6-7 hours.

What I'm thinking is, is the ARPA file alright? Like there has been no error message whatsoever; hence I should not doubt the generation of ARPA; still is there any command to check the integrity of the generated ARPA file?

Regarding RAM, I've a 16GB RAM and ARPA is a 68GB file. Not sure how the arpa to binary process work, but as you said, if it were for RAM, there should've been some killer initiated. But none were there, not in dmesg at-least.

Finally, for the data structure, do you then suggest I go for trie structure with default (dynamic) quantization?

**Comment by kpu** [comment]
`build_binary` prints an error when the arpa is broken. Read the documentation I linked to. Run `build_binary foo.arpa` for a memory estimate with various sizes. I bet the memory estimate for probing is above 16 GB.  
Issues are for software bugs not individual support requests.
