### ISSUE TITLE
How to calculate the current word score of different sentence in a mini-batch ?

### ISSUE THREAD

**Issue by PlayDeep** [kpu/kenlm#202]
Thank you for your work and release your code. As described in title, I want to get the mini batch scores to speed up and then I can effective use it in a neural model.

**Comment by kpu** [comment]
I think you are asking for p(* | context) as a vector over words.  Whilst you can use the State objects to obtain some speed up in running a for loop, kenlm isn't optimized for this use case because it is a reverse trie implementation.  You want a forward trie.  Looking forward to the pull request.
