### ISSUE TITLE
Hello world: KenLM basic usage (+python)

### ISSUE THREAD

**Issue by nadavb** [kpu/kenlm#203]
Hi,
I am trying to use KenLM. I installed using `sudo pip install https://github.com/kpu/kenlm/archive/master.zip`

I have a file (tab seperated, or any format that KenLM can accept) in this structure (for 5-gram):
w1 w2 w3 w4 w5 frequency

How do I create a KenLM data structure, preferably from python, or any other option that may exist?
Afterwards, I want to load the KenLM structure to the RAM (using `model = kenlm.Model('lm/file.arpa')` for example), and get the frequency of the n-gram. If it's not possible, then getting the log frequency would suffice as well.

What's the right way to start? Would the pip installation be enough, or do I need another build?

In addition, does KenLM supports top-k queries? Like what is the most probable ten words after a known 3-gram context for example?

**Comment by kpu** [comment]
5-gram counts alone, without any padding at the beginning of sentence, are insufficient information to construct a language model.  For example, a one-word sentence should impact probabilities but cannot be encoded in your representation.  

It's not clear from your question if you want a language model with smoothed probabilities (in which case run https://kheafield.com/code/kenlm/estimation/ on plain text) or just want somebody to store your 5-gram counts for you (in which case it sounds like you just want a hash table).

**Comment by nadavb** [comment]
@kpu Thanks, what I meant is that I already have the ngrams. For example, the Google Books ngrams. I want to take the already created ngrams statistics into the KenLM, so I can perform queries on it.

**Comment by kpu** [comment]
Google n-grams are pruned so one can't build a Kneser-Ney model (which counts singletons etc).  But fear not: http://statmt.org/ngrams/ .

**Comment by nadavb** [comment]
Google also published the 1-gram -> 5->gram, wouldn't that make the Kneser-Ney model building possible?

**Comment by kpu** [comment]
No.  Read https://kheafield.com/papers/stanford/crawl_paper.pdf .

**Comment by nadavb** [comment]
Thanks! Appreciated!
