### ISSUE TITLE
tokenizing a different language

### ISSUE THREAD

**Issue by isaacleeai** [kpu/kenlm#204]
I have seen other issues where you have suggested using the [moses tokenizer](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl). Unfortunately, I am tokenizing korean so moses won't work. Could you post an examble of the input `text` file  in `bin/lmplz -o 5 <text >text.arpa`?

Btw, I have seen your corpus formatting notes, and this is a set of rules I have now.
	1. Words are delimitated by one of `'\0', '\t', '\r', ' '`
	2. Lines are delimitated by `'\n'`
	3. use `utf-8` encoding
	4. Remove any training symbols — `<s>, </s>, <unk>` — because these are added internally, or turn on `--skip_symbols`

An example of such input file in English would tremendously help!
Thanks

**Comment by kpu** [comment]
https://www.elastic.co/blog/using-korean-analyzers

Example input:
```
this is a sentence .
here is another sentence .
tokenizers split , off for you !
```

**Comment by isaacleeai** [comment]
Would this be correct?
along with the 4 rules mentioned above, these are additional formatting rules for the input to `bin/lmplz
5. can have special characters, and there needs to be space around special character when there are texts on both sides.
6. each sentence MUST end with either of `.`, `!`, `?`

Thanks!

**Comment by Khanifsaleh** [comment]
ca

> lmplz is not a tokenizer. You tokenize it.
> A sentence is a line. A space delimits tokens. That's all I care about.
> The example I gave is tokenized.

for some reasons, can I change space (for delimits tokens) with another token? i.e "|"
