### ISSUE TITLE
error: File /dev/null isn't normal. when run lmplz 

### ISSUE THREAD

**Issue by sty1992928** [kpu/kenlm#205]
I installed KenLM successfully. 
And when I just run 'bin/lmplz -o 5 <text >text.arpa' as the document said, error occurs: 

**=== 1/5 Counting and sorting n-grams ===
File /dev/null isn't normal.  Using slower read() instead of mmap().  No progress bar.
/home/wjp/kenlm/util/file.cc:183 in std::size_t util::PartialRead(int, void*, std::size_t) threw FDException because `ret < 0'.
Bad file descriptor in /dev/null while reading 6 bytes in file /dev/null**

Is there anybody meet the same error?
please, I need help, this is killing me.

**Comment by kpu** [comment]
Where is your corpus?

**Comment by sty1992928** [comment]
sorry, I run an order:  lmplz -o 5 tmp.txt tmp.arpa. 
just like the example on your website

**Comment by sty1992928** [comment]
My fault, it works when I add --text and --arpa, I'm too supid...
