### ISSUE TITLE
./bin/lmplz command not proceeding

### ISSUE THREAD

**Issue by Demfier** [kpu/kenlm#206]
Hi,

I've run into a strange issue. When I first installed the library, compiled and built a language model, everything was working just fine. But now when I try to run `./bin/lmplz -o 4 /path/to/text_file > /path/to/save/language_model` again, the output is stuck at:

```
=== 1/5 Counting and sorting n-grams ===
File /dev/pts/17 isn't normal.  Using slower read() instead of mmap().  No progress bar.
```

The same command (with the same file) finished within a minute or so when I tried it for the first time.

I am using Ubuntu 16.04 and have installed the library following the instructions [here](https://kheafield.com/code/kenlm/) (along with its dependencies). I understand this could possibly be an issue with my system but I am unable to figure as to where exactly do I point out. Any help would be greatly appreciated.

Thanks,
Gaurav.

**Comment by hieuhoang** [comment]
you have to give text_file to standard in.
  /bin/lmplz -o 4 < /path/to/text_file > /path/to/save/language_model

**Comment by Demfier** [comment]
Oh, you are correct! Thank you very much and here I was investigating if there was something wrong with my terminal.
