### ISSUE TITLE
How kenlm work on subword/wordpiece. would you suggest a command line? thanks.

### ISSUE THREAD

**Issue by bjtommychen** [kpu/kenlm#219]

**Comment by kpu** [comment]
`--discount_fallback` should be all you need to deal with finite vocabulary.  It will still generate `<unk>` though.

**Comment by bjtommychen** [comment]
Thanks. one more question.
The SubWords system will convert 'hello world' into '_he llo _w or ld'
Is kenlm tools still be suitable for this? 
and for subword, kenlm will treat it as character-based or not?
Thanks.

**Comment by kpu** [comment]
The tokens are anything separated by whitespace.  Where you choose to put whitespace is your choice / problem.
