### ISSUE TITLE
Invalid argument munmap failed[1] while running C++ example

### ISSUE THREAD

**Issue by unnikrishnanta** [kpu/kenlm#222]
I was running the C++ example feeding in the words from a vector.  
```
#include "lm/model.hh"
#include <iostream>
#include <string>
using namespace std;
int main() {
  using namespace lm::ngram;
  Model model("bible.klm");
  State state(model.BeginSentenceState()), out_state;
  const Vocabulary &vocab = model.GetVocabulary();
  vector<string> sent = {"this", "is", "a", "test"};
  float total_score = 0;
  for(auto word: sent){
    cout << "Word: " << word << "\n";
    auto idx = vocab.Index(word);
    auto score = model.Score(state, idx, out_state);
    total_score += score;
    state = out_state;
  }
  cout << "Total score: " << total_score << "\n";
}
```
After printing `total_score`, I am getting 
```
/kenlm-master/util/mmap.cc:145 in void util::UnmapOrThrow(void *, size_t) threw ErrnoException because `munmap(start, length)'.
Invalid argument munmap failed[1]
```

This is the output from the program: 
```
Word: this
Word: is
Word: a
Word: test
Total score: -8.20225
./kenlm-master/util/mmap.cc:145 in void util::UnmapOrThrow(void *, size_t) threw ErrnoException because `munmap(start, length)'.
Invalid argument munmap failed[1]    59594 abort      ./example
```
I am running it on MacOs 10.14.4

**Comment by kpu** [comment]
That's not good.  Is this model ARPA or binary?  

In the latest master, I just pushed more debugging information for `munmap` so the error should be more verbose.  

On OS X by default it should be doing `malloc` followed by `read` so in `scoped_memory::reset` it should be taking the `MALLOC_ALLOCATED` branch and never calling `munmap`.  

In line `util/mmap.cc` near line 79 edit it like so:
```
  data_ = data;
  size_ = size;
  source_ = source;
  if (source_ == MMAP_ALLOCATED || source_ == MMAP_ROUND_UP_ALLOCATED) {
    abort();
  }
}
```
Then can you give me a backtrace of the first crash?

**Comment by unnikrishnanta** [comment]
Thanks for your reply. My model was binary and it was getting aborted at 
```
if (source_ == MMAP_ALLOCATED || source_ == MMAP_ROUND_UP_ALLOCATED) {
    abort();
  }
```
Unfortunately, I am not able to reproduce the error anymore. I can't seem to remember what did I do earlier that was giving me the error. I will be happy to provide a dump if it happens again. 

Just to be sure, the correct approach to set KENLM_MAX_ORDER in cmake is 

`cmake .. -DKENLM_MAX_ORDER=10 -DCMAKE_BUILD_TYPE=Release` and during compiling, I can pass the flag `-DKENLM_MAX_ORDER=3` to use 3 grams. 

Sorry if it is too basic. It will be extremely useful if there was an advanced C++ example.

**Comment by kpu** [comment]
No, bad.  Always use the same `-DKENLM_MAX_ORDER` when compiling and using the library.

**Comment by mahjabeen-sust** [comment]
I am trying a build a language model in mosesdecoder. I faced the same problem: util/mmap.cc:145 in void util::UnmapOrThrow(void*, size_t) threw ErrnoException because `munmap(start, length)'.
@unnikrishnanta how did you finally solved it?
