### ISSUE TITLE
Could NOT find Eigen3 on macOS10.14.5

### ISSUE THREAD

**Issue by Zacharyyyy** [kpu/kenlm#226]
it keep showing the following message when I try to cmake it, even after I followed what it instructed me to do.
************
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
CMake Warning at lm/interpolate/CMakeLists.txt:65 (message):
  Not building interpolation.  Eigen3 was not found.

-- To install Eigen3 in your home directory, copy paste this:
export EIGEN3_ROOT=$HOME/eigen-eigen-07105f7124f9
(cd $HOME; wget -O - https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 |tar xj)
rm CMakeCache.txt
************
no matter how I tried, it kept showing this message. But somehow, it does work when I execute "make -j2". and I can nw train model out of it.

**Comment by kpu** [comment]
As the message indicates, it's `Not building interpolation.`  If you don't care about log-linear interpolation, this is fine.  
Regarding "no matter how I tried" did that include running the commands suggested in the message?

**Comment by Zacharyyyy** [comment]
Thank you for explaining, that makes much more sense.
And yes, I did try the suggested commend. the following is what I did.(I only change "wget" to "curl",, since it's mac)

export EIGEN3_ROOT=$HOME/eigen-eigen-07105f7124f9
(cd $HOME; curl - O  https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 |tar xj)
rm CMakeCache.txt

**Comment by kpu** [comment]
Regarding curl you don't want `- O`.  Just `curl https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2`
