### ISSUE TITLE
Basic usage: sentence markers, usage of build_binary

### ISSUE THREAD

**Issue by anetschka** [kpu/kenlm#229]
This is a request for documentation/explanation. I have built a toy model, but when I try to load the arpa file in Python, I get  an exception for a missing sentence marker. It is also recommended for faster loading to build a model binary, choosing, if I want to, to suppress errors for missing sentence markers. I have a couple of questions on this that could maybe be answered in the wiki (?, ready to add that myself):
1. Which sentence markers exactly are expected? I tried <s>sentence content.</s>, but this does not seem to work?
2. How can I load the binary from Python?
3. How to use build_binary? More precisely, how to retrieve the output? I checked build_binary -h, but without finding an answer.

**Comment by kpu** [comment]
The basic usage, ignoring python, is here: https://kheafield.com/code/kenlm/
1. The following tokens are special: begin of sentence `<s>`, end of sentence `</s>`, and unknown word `<unk>`.  
2. Same way you load an ARPA file.  Just change the file name.  
3. `build_binary in.arpa out.binary` then pass `out.binary` as the file name in python.

**Comment by anetschka** [comment]
Thanks for this amazing software, @kpu. I am not through with testing yet, but for what I have seen so far, it looks like a very good project!
