### ISSUE TITLE
How to get arpa file when using interpolate?

### ISSUE THREAD

**Issue by houxy12** [kpu/kenlm#230]
Hello, @kpu Thanks for your contribution. I use interpolate command to merge a few .intermediate file , but I don't know how to get arpa file after interpolation.  The following is my command.
interpolate -S 10% -T temp -m set{1,2,3,4}.intermediate -t text.txt >word_level_5.arpa

**Comment by kpu** [comment]
I'm confused.  The ARPA is on stdout.  So `word_level_5.arpa` is the ARPA file you are looking for.
