### ISSUE TITLE
Argument for maximum ngram order in setup.py

### ISSUE THREAD

**Issue by lpla** [kpu/kenlm#236]
https://github.com/kpu/kenlm/blob/401c6a9f6c53b7ee03b194b8b5632a6842fe5846/setup.py#L24

In Bicleaner, devs needed to set ['-DKENLM_MAX_ORDER=7'](https://github.com/bitextor/kenlm/blob/d3f1487351aace071affff7f158bb439a9098131/setup.py#L24) and the solution was forking `kenlm` for that. I would like to avoid forking projects to change one hardcoded parameter, but I don't know how to properly provide an argument to setup.py in `kenlm`, given that setuptools are badly documented.

People in SO try to do it in this way: https://stackoverflow.com/questions/677577/distutils-how-to-pass-a-user-defined-parameter-to-setup-py

Also it can be done with environment variables: https://stackoverflow.com/questions/54467648/python-setup-py-set-environment-variable-prior-to-running-install-requires

Any suggestion? I would like to do the pull request, but I prefer discussing this before coding it.

**Comment by kpu** [comment]
I'd be happy with a command-line argument to `setup.py`

**Comment by kpu** [comment]
According to whatever method for setup.py to read an argument since they all seem a bit weird

**Comment by lpla** [comment]
So, something hacky like this? https://stackoverflow.com/a/4792601/2339931

**Comment by kpu** [comment]
Fixed by merge I presume
