### ISSUE TITLE
Unable to generate document specific language model

### ISSUE THREAD

**Issue by bluemonk482** [kpu/kenlm#244]
I am using [DSAlign](https://github.com/mozilla/DSAlign) for speech alignment, which uses kenlm for language modeling. However I cannot seem to generate document specific language model. 

I get the error below occurs. Is this because my script file does not contain enough words? The `.arpa` file is empty. Do I need add `--discount_fallback`?

> DEBUG:root:Start
> DEBUG:root:Looking for model files in "models/en"...
> DEBUG:root:Loading alphabet from "models/en/alphabet.txt"...
> === 1/5 Counting and sorting n-grams ===
> Reading /mnt/sdb/Tools/DSAlign/data/14001.txt.clean
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ****************************************************************************************************
> Unigram tokens 3370 types 698
> === 2/5 Calculating and sorting adjusted counts ===
> Chain sizes: 1:8376 2:31559028736 3:59173183488 4:94677090304 5:138070753280
> /mnt/sdb/Tools/DSAlign/dependencies/kenlm/lm/builder/adjust_counts.cc:52 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `s.n[j] == 0'.
> Could not calculate Kneser-Ney discounts for 5-grams with adjusted count 4 because we didn't observe any 5-grams with adjusted count 3; Is this small or artificial data?
> Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback
> 
> Traceback (most recent call last):
>   File "/mnt/sdb/Tools/DSAlign/align/align.py", line 653, in <module>
>     main()
>   File "/mnt/sdb/Tools/DSAlign/align/align.py", line 563, in main
>     '5'
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['dependencies/kenlm/build/bin/lmplz', '--text', 'data/14001.txt.clean', '--arpa', 'data/14001.txt.arpa', '--o', '5']' died with <Signals.SIGABRT: 6>.

**Comment by bluemonk482** [comment]
Ok, problem sorted by adding `--discount_fallback`

**Comment by kpu** [comment]
Ok, but your training data is still too small to train a 5-gram model with.
