### ISSUE TITLE
macos Help: error  library not found for -lThreads::Threads

### ISSUE THREAD

**Issue by dfbblwd** [kpu/kenlm#249]
using macos, 
while make -j 4:
error showed as below:

Linking CXX executable ../tests/file_piece_test
ld: library not found for -lThreads::Threads

**Comment by kpu** [comment]
Did any other executables fail to compile?  Can you do make VERBOSE=1 ?  I've disabled test compilation by default, so if this is still and issue for you, feel free to reopen.
