### ISSUE TITLE
chain issue

### ISSUE THREAD

**Issue by YuBeomGon** [kpu/kenlm#255]
hi,
~/kenlm/build/bin/lmplz -o 7 < total.txt > zeroth.11gram.arpa
above is ok
but ~/kenlm/build/bin/lmplz -o 8 < total.txt > zeroth.11gram.arpa
error is like below.
Chain sizes: 1:14472 2:336301472 3:630565248 4:1008904384 5:1471318912 6:2017808768 7:2648374016 8:3363014656 9:4161730816 10:5044521984 11:6011388928
/home/beomgon/kenlm/lm/builder/adjust_counts.cc:60 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
ERROR: 7-gram discount out of range for adjusted count 3: -0.13095593
Aborted (core dumped)

I checked my text, each line has more than 12 space.
so what is wrong??
when I see the code, there is TODO message,
is it need to change code ??

          for (unsigned j = 1; j < 4; ++j) {
            // TODO: Specialize error message for j == 3, meaning 3+
            UTIL_THROW_IF(s.n[j] == 0, BadDiscountException, "Could not calculate Kneser-Ney discounts for "
                << (i+1) << "-grams with adjusted count " << (j+1) << " because we didn't observe any "
                << (i+1) << "-grams with adjusted count " << j << "; Is this small or artificial data?\n"
                << "Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback\n");
          }

**Comment by kpu** [comment]
Welcome to Kneser-Ney smoothing.  Your data violates Kneser-Ney smoothing assumptions probably because it's too small for 8-grams.  If you really really want to, use `--discount_fallback` to make stuff up.  The TODO is literally to add a + sign to the message in the case of j = 3.
