### ISSUE TITLE
Change directory to save temporary files. 

### ISSUE THREAD

**Issue by victornoriega** [kpu/kenlm#256]
I've created a few trigrams models with different datasets with no problem, but I can't create higher orders ngram models because of disk space in /tmp/. I'm not a sudo user so I shouldn't mess with the files in /tmp/ (I may remove a few files, but the admin will get me banned). And the disk that got the /tmp/ folder only got around 30 GB left. 

My question is: can I change the directory where I save temporary files? I need it somewhere else than /tmp/. Thank you.

**Comment by hieuhoang** [comment]
looking at
   lmplz --help
the arg -T seems to be what you need

**Comment by victornoriega** [comment]
I'm currently trying this. If anything happens I will tell you.

**Comment by victornoriega** [comment]
That worked, thank you.
