### ISSUE TITLE
ubuntu 18.04 ，"cmake .."   error：

### ISSUE THREAD

**Issue by Judonlee** [kpu/kenlm#257]
**ubuntu 18.04 ，“cmake ..”error：**
```bash
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
...
-- Configuring incomplete, errors occurred!
See also "/home/MyExperimentLab/KenLM_space/kenlm/build/CMakeFiles/CMakeOutput.log".
See also "/home/MyExperimentLab/KenLM_space/kenlm/build/CMakeFiles/CMakeError.log".
```

I have solved the problem according to the method given by the author. Please refer to the method given by @kpu  for details.

**Comment by axchanda** [comment]
@Judonlee I believe you need to specify the path where Boost libraries are installed, for the installation to complete!

**Comment by danyaljj** [comment]
same error here on Ubuntu 16.04.6 LTS

**Comment by swarajbadhei** [comment]
Installed all the prerequisites but still the same issue. Please provide some solution.

**Comment by Shridharpawar77** [comment]
Hello guys did you found any solution?

**Comment by kpu** [comment]
I'm confused.  The above commands install the correct dependencies.  Why do they need to be done inside a docker instead of just installing the correct dependencies?  

Install `libboost-all-dev`

https://neural.mt/code/kenlm/dependencies/

**Comment by Judonlee** [comment]
> I'm confused. The above commands install the correct dependencies. Why do they need to be done inside a docker instead of just installing the correct dependencies?
> 
> Install `libboost-all-dev`
> 
> https://neural.mt/code/kenlm/dependencies/



> Hello guys did you found any solution?

Install libboost-all-dev

It's worked for me. Maybe you also have errors due to GCC version, please switch GCC version.
