### ISSUE TITLE
Not the usual perplexity...

### ISSUE THREAD

**Issue by mlforcada** [kpu/kenlm#260]
The code that computes perplexity [https://github.com/kpu/kenlm/blob/f5458d09e54ee7c00485436137328b1ba24f56e5/python/kenlm.pyx#L198] does so by exponentiating 10 to minus the score of the sentence divided by its length in words. The score [https://github.com/kpu/kenlm/blob/f5458d09e54ee7c00485436137328b1ba24f56e5/python/kenlm.pyx#L142] is the logarithm in base 10 of the probability of the sentence. Therefore, what this computes is not what most of us would call perplexity, namely: 

10^{-p(x)\log_{10} p(x)}

(the base of  course can be 2, or e or whatever). Should this be corrected?

**Comment by kpu** [comment]
The python code appears to provide the same output as the C++ code.  

Perplexity is the cross entropy of the model distribution given the data distribution.  So you don't want 10^{-p(x)\log_{10} p(x)}, you want 10^{-\sum_x d(x)\log_{10} p(x)} where $d$ is the true distribution of language.  

In practice the data is a test set.  So 10^{-\frac{1}{|w|} \sum_i d(w_i | w_1^{i-1})\log_{10} p(w_i | w_1^{n-1})}

**Comment by mlforcada** [comment]
You are absolutely right. I had confused "perplexity of a probability distribution" with "perplexity of a probability model". Thanks a million!
