### ISSUE TITLE
query outputs final stats to STDOUT

### ISSUE THREAD

**Issue by emjotde** [kpu/kenlm#275]
Hi,
This is appended to STDOUT when running `query` and while doing line-by-line processing.

```
Perplexity including OOVs:      7179.727316592978
Perplexity excluding OOVs:      7179.727316592978
OOVs:   0
Tokens: 2
```

Cost me a lot of time to debug or even realize that my lines do not align when using with GNU parallel. Maybe make these optional, or suppressible?

Alternatively having to do `cat file.txt | query bla.bin | head -n -4` is not great when not actually remembering that one has to do it :)

**Comment by kpu** [comment]
Pull request?

**Comment by emjotde** [comment]
Taking a screenshot of this :P

**Comment by kpu** [comment]
I'll need you to add and edit the changelog.

**Comment by kpu** [comment]
I've added more controls.  The default is still to print everything but the behavior of `-v sentence` now just prints sentence lines.

**Comment by emjotde** [comment]
`-v words` is technically a line-by-line processor, too, isn't it?

**Comment by kpu** [comment]
Yes.

**Comment by emjotde** [comment]
Which is where I actually ran into this. Forgot to mention explicitly.

**Comment by ririxox** [comment]
Hi, can you please tell me how to calculate the perplexity including OOVs? or is there a script for that?
