### ISSUE TITLE
ERROR: 4-gram discount out of range for adjusted count 3: -2.7044096

### ISSUE THREAD

**Issue by krutika23** [kpu/kenlm#277]
python3 generate_lm.py --input_txt working/training_material/vocabulary.txt  --output_dir . --top_k 500000 --kenlm_bins /home/krutika/DeepSpeech-0.7.0/kenlm/build/bin/ --arpa_order 5 --max_arpa_memory "85%" --arpa_prune "0|0|1" --binary_a_bits 255 --binary_q_bits 8 --binary_type trie

Running this command gives me the error:
ERROR: 4-gram discount out of range for adjusted count 3: -2.7044096
Traceback (most recent call last):
  File "generate_lm.py", line 210, in <module>
    main()
  File "generate_lm.py", line 201, in main
    build_lm(args, data_lower, vocab_str)
  File "generate_lm.py", line 101, in build_lm
    *args.arpa_prune.split("|"),
  File "/home/krutika/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/krutika/DeepSpeech-0.7.0/kenlm/build/bin/lmplz', '--order', '5', '--temp_prefix', '.', '--memory', '85%', '--text', './lower.txt.gz', '--arpa', './lm.arpa', '--prune', '0', '0', '1']' died with <Signals.SIGABRT: 6>.

**Comment by kpu** [comment]
Your corpus is too small.  Use `--discount_fallback` if you really want.

**Comment by elahimanesh** [comment]
> Your corpus is too small. Use `--discount_fallback` if you really want.

unrecognised option --discount_fallback

why?

bzcat lm_data.txt.bz2 |  python preprocess.py |  bin/lmplz -o 3 --discount_fallback > lm_data.arpa
