### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SaintLogos1234** [kpu/kenlm#282]
I install kenlm according to the following command:
mkdir build
cd build
cmake ..
make
python setup.py install
the compilation is successful, but I run python setup.py install，the following error appears, what is going on:
![image](https://user-images.githubusercontent.com/19261529/84371463-47a80480-ac0c-11ea-9e11-d64ba03b3625.png)
How to resolve the above errors

**Comment by kpu** [comment]
Please post full output as text, not a limited screenshot.  Nonetheless, it looks like your bzip2 wasn't compiled with `-fPIC`.  Based on the path it looks like you compiled bzip2 yourself?  

If you don't care about bzip2 support, comment out lines 41-43 of `setup.py`.

**Comment by SaintLogos1234** [comment]
Thank you very much. It seems that your suggestion is correct. After installing your suggestion, the modification has been successfully installed. At the same time, I took the liberty to ask me. After installing the 41-43 comment, does it have a great impact on subsequent use? Finally, I am very sorry for the confusion caused by my non-standard questions
