### ISSUE TITLE
error when loading shared library

### ISSUE THREAD

**Issue by raviolli** [kpu/kenlm#287]
I'm getting this error when using kenlm. I have it working on other systems. 

**_error while loading shared libraries: libboost_program_options.so.1.58.0_**

I also installed this:

**_sudo apt-get install build-essential libboost-all-dev cmake zlib1g-dev libbz2-dev liblzma-dev_** 

Is there some weird issue with dependency at compile time for kenlm?

**Comment by kpu** [comment]
Smells like you compiled with an older boost, upgraded boost, and now it's missing the version the binary was compiled with.  Recompile.

**Comment by raviolli** [comment]
Hi Ken, thanks for helping me out with this...
I recompiled it and it just can't seem to locate the library. Are how you search for the library.. is there a default path or something I should know of?

**_./lmplz: error while loading shared libraries: libboost_program_options.so.1.72.0: cannot open shared object file: No such file or directory_**

**Comment by kpu** [comment]
How is boost installed?  If I had to guess, it's in your home directory or something.  In which case, you need to set LD_LIBRARY_PATH to the directory that file is found.

**Comment by raviolli** [comment]
Thanks, 

I have it installed in the lower level of the File system and have soft links to it through my environment. 

Thanks it was the LD_LIBRARY_PATH. 

I set the PATH but it didn't work..
