### ISSUE TITLE
can not import kenlm 

### ISSUE THREAD

**Issue by Nanamumuhan** [kpu/kenlm#295]
![图片](https://user-images.githubusercontent.com/41236260/92109496-b5cf2280-ee1b-11ea-8be0-726f06a2f97d.png)
install the kenlm but can not import it.

**Comment by kpu** [comment]
You've compiled kenlm with different python libraries than the python you are using.  Suggest https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa instead of anaconda.
