### ISSUE TITLE
How to iterate a state's all words in kenlm 

### ISSUE THREAD

**Issue by lsdustc** [kpu/kenlm#297]
Dose kenlm  have a interface that can iterate all word in a state's next jump . I cannot find it in lm/virtual_interface.hh and lm/model.hh

**Comment by kpu** [comment]
Inherit from `EnumerateVocab` in `lm/enumerate_vocab.hh` then pass the pointer in the `enumerate_vocab` variable of `Config` that you pass to the `Model` constructor.

**Comment by kpu** [comment]
Did I understand the question correctly?  The language model permits every word following a state with some probability....  Are you asking for the words in the State?  

If you want an efficient array of all words given a context, unfortunately the reverse trie data structure isn't really setup for that.
