### ISSUE TITLE
Character Level LM to correct words

### ISSUE THREAD

**Issue by amitbcp** [kpu/kenlm#302]
I am using https://github.com/parlance/ctcdecode for decoding. My predictions are at word level only as input/probability map are for single words. 
Can you suggest how do I create a LM for words ? My text files currently only single words per line

**Comment by kpu** [comment]
Either do a word level model on sentences or map space to a special token and train a character level model?

**Comment by amitbcp** [comment]
@kpu  can you please give an example for the second option you suggested ?
Currently I preprocessed my text file to  something like this : (Each character is separated by space)

i t e m
I t e m
M a r k s
M a t e r i a l
M o t o r
M R P

And using the below model for Kenlm, were the test.txt is the sample text given above. 
```bin/lmplz -o 3  <test.txt >text.arpa```

Is this is what you are referring to or something else ? Sorry for so many questions, I am still trying to understand these parts in full detail

**Comment by kpu** [comment]
That will build a character-level model.  As a generalization to include words:
```
T h i s <space> i s <space> a <space> s e n t e n c e <space> .
```
Otherwise I don't understand what you are asking for.

**Comment by amitbcp** [comment]
@kpu I want to build a character-level model, as I just want to predict the right words independently of other words. Though the n-gram probability of LM would help in getting the right word. 

I am using the LM in Recognizer of an OCR during the CTCDecoding. The Recognizer gets single word as input only, so it never sees whole sentences.

I guess in this use case, character level model would work right ?  And the sample text to build Character Level model would be like the one I gave or does it needs any further changes ?

And thank you so much for the replies and help.
