### ISSUE TITLE
During the run time how would I know the likelihood probability of a particular ngram (word) given by the language model

### ISSUE THREAD

**Issue by vchagari** [kpu/kenlm#320]
Background: 
I am running Deepspeech to convert an audio into a speech, an audio contains nouns which I want to get transcribed into the text. Deepspeech has a feature to give hints (so called hot-words) to the decoder along with a boost value which would help decoder to provide accurate results. To know what boost value to provide, one should know the likelihood probability of that particular ngram/word give by the language model, since Deepspeech uses Kenlm, I am asking here to see if there an api (python/c++) which takes a word or n words and provide the likelihood probability of the words. 
Please provide inputs/thoughts/suggestions, thank you for your help.

**Comment by kpu** [comment]
There is an API.  See Querying on https://kheafield.com/code/kenlm/

**Comment by vchagari** [comment]
Hi @kpu, 
Thanks, but I couldn't find a blog where I can post my questions, could you please help pointing out to me to the right resource (doc/website). I am also looking for a documentation on the usage using python.
Thank you

**Comment by kpu** [comment]
Have you tried the project README?  https://github.com/kpu/kenlm/blob/master/README.md#basic-usage

**Comment by vchagari** [comment]
I have seen it, thank you though, but it only shows basic usage, I was looking for more examples (including c++).
