### ISSUE TITLE
Kenlm 

### ISSUE THREAD

**Issue by TEJASK111** [kpu/kenlm#321]
How can I compile kenlm using cygwin in windows 10.

**Comment by kpu** [comment]
Windows is not supported.  Submit a pull request.

**Comment by TEJASK111** [comment]
Kenlm is not supported in windows?

**Comment by kpu** [comment]
It might work, it might not.  But I don't spend any time ensuring it does.  The community contributes code from time to time.

**Comment by hieuhoang** [comment]
Use wsl2 instead o of cygwin
  https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by TEJASK111** [comment]
@hieuhoang  you mean that I can  compile kenlm in wsl . So can I use it in windows or I have to use it in wsl only.

**Comment by hieuhoang** [comment]
Ah, you can compile kenlm in wsl2 like it was Linux. But you can't use it
in a windows application

**Comment by TEJASK111** [comment]
@hieuhoang thanks for help
