### ISSUE TITLE
Rust bindings for kenlm?

### ISSUE THREAD

**Issue by poneill** [kpu/kenlm#325]
Hi,

I'm looking into writing rust bindings for kenlm.  I'm posting this issue to check to see:

a) if there's been any previous work done on this topic
b) if the bindings would be a welcome addition to the main kenlm repo
c) (if no to a and yes to b) if anyone else with expertise in rust is interested in this project and would like to collaborate.

Cheers,
Pat.

**Comment by kpu** [comment]
a) Not to my knowledge.  The most likely people would be Mozilla but deepspeech binds from python if I understand correctly.  
b) Sure
c) I have no Rust experience

**Comment by poneill** [comment]
Thanks, I'll PR when I have something working.

**Comment by poneill** [comment]
To follow up, rust/c++ interop doesn't seem to be at a point where it makes sense for my use case, so I'll have to put this aside for now.
