### ISSUE TITLE
rewindable stream does not detect overrun when blocks are recycled

### ISSUE THREAD

**Issue by kpu** [kpu/kenlm#33]
The current RewindableStream implementation can cycle through blocks with operator++ then not detect an overrun because the same memory block has been recycled.

**Comment by skystrife** [comment]
So this is a problem when there is, say, only one block on a chain? Or is this something different?

**Comment by kpu** [comment]
I only had one block on the chain at the time.  Which may be a bad corner case.

**Comment by kpu** [comment]
Actually it's an impossible case.  I've added a BlockCount method to Chain.  Guess I'll make it abort.

**Comment by kpu** [comment]
Fixed in 9ab07ff648fbd186afd9fb251abf10c8196a1cf8
