### ISSUE TITLE
How can I decrease memory requirement when loading model?

### ISSUE THREAD

**Issue by ulucsahin** [kpu/kenlm#335]
First of all thanks for the clean repository.

I have created a 3-gram model from 400mb of text. I also pruned it so my model size on disk is 67mb. However, when I try to load it, it uses about 2.4 GB of ram. This is completely fine on my desktop, but I need to run it in a device with low memory. I also tried converting .arpa to .binary, but memory requirement did not change. Anything I can do to decrease memory requirement?

Thanks!

**Comment by kpu** [comment]
Run `build_binary your.arpa` (without the output file name) for a free consultation on the memory size with various compression options.
