### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by v-yunbin** [kpu/kenlm#336]
1. I have  install  eigens but it can not  find  it.
2. TARGETS given target "kenlm" which does not exist .
```
`CMake Warning at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "Eigen3" (requested
  version 3.1.0) with any of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
Boost 1.41.0 found.
Found Boost components:
   program_options;system;thread;unit_test_framework
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found ZLIB: /home/ybZhang/miniconda3/lib/libz.so (found version "1.2.11")
-- Found BZip2: /usr/local/lib/libbz2.a (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /home/ybZhang/miniconda3/lib/liblzma.a
-- Looking for lzma_auto_decoder in /home/ybZhang/miniconda3/lib/liblzma.a - found
-- Looking for lzma_easy_encoder in /home/ybZhang/miniconda3/lib/liblzma.a
-- Looking for lzma_easy_encoder in /home/ybZhang/miniconda3/lib/liblzma.a - found
-- Looking for lzma_lzma_preset in /home/ybZhang/miniconda3/lib/liblzma.a
-- Looking for lzma_lzma_preset in /home/ybZhang/miniconda3/lib/liblzma.a - found
-- Found LibLZMA: /home/ybZhang/miniconda3/include (found version "5.2.5")
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
CMake Error at CMakeLists.txt:116 (install):
  install TARGETS given target "kenlm" which does not exist in this
  directory.


-- Configuring incomplete, errors occurred!

`
```

**Comment by DewiBrynJones** [comment]
I had the same build error until I updated cmake to the latest version - 3.20.2

See https://cmake.org/download/ or https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

**Comment by b0r3k** [comment]
> I had the same build error until I updated cmake to the latest version - 3.20.2

Thanks a lot, solved for me! 

I'll add that if you for some reason need to use `cmake` from older OS, you can download it from the cmake website and install it from .sh or something.

**Comment by kpu** [comment]
@jacobkahn Can we unbork older cmake?

**Comment by jacobkahn** [comment]
@kpu I'll take a look ASAP - I tested with CMake back to 3.5, but I'll go back further.

**Comment by jsilbergDS** [comment]
Thanks, both, for jumping on this so quickly! Updating to cmake 3.20 worked, thanks! 

If anyone comes across this post and is trying to compile on Google Colab, I used method B linked here to update to 3.20 (just running apt-get couldn't find 3.20): https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

Within the code for Method B, I hard-coded the version and build numbers as Colab was throwing errors with trying to use variables.

**Comment by v-yunbin** [comment]
> I had the same build error until I updated cmake to the latest version - 3.20.2
> 
> See https://cmake.org/download/ or https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

it works for errors "ARGETS given target "kenlm" which does not exist"
but i still get errors "-- Could NOT find Eigen3 (missing: Eigen3_DIR)"
do you have some suggests?

**Comment by v-yunbin** [comment]
> > I had the same build error until I updated cmake to the latest version - 3.20.2
> > See https://cmake.org/download/ or https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line
> 
> @DewiBrynJones it works for errors "ARGETS given target "kenlm" which does not exist"
> but i still get errors "-- Could NOT find Eigen3 (missing: Eigen3_DIR)"
> do you have some suggests?

**Comment by v-yunbin** [comment]
For error "Could not find a package configuration file provided by "Eigen3""
you can make with adding the option “-Eigen3_DIR” to specify Eigen3" your installation path
CC=gcc CXX=g++ cmake .. -DEigen3_DIR=../../eigen3-master/build/
