### ISSUE TITLE
How to create 3-gram.pruned.3e-7.arpa?

### ISSUE THREAD

**Issue by kouohhashi** [kpu/kenlm#337]
Hi,
I know this is not an issue but I put it because I don't know where to post...

I want to create 3-gram.pruned.3e-7.arpa with LibriSpeech datasets by myself.
I can do it with default options but the size of arpa file was huge.

Could some give me how to successfully create pruned ( small file size ) model?

BTW, 3-gram.pruned.3e-7.arpa is on [openslr.org](3-gram.pruned.3e-7.arpa).

**Comment by kpu** [comment]
That exact file was not built with kenlm.  Mine always have `<unk>` as the first entry.  You are, however, welcome to use the `--prune` option on https://neural.mt/code/kenlm/estimation/ .  It does count based pruning not probability threshold based pruning.
