### ISSUE TITLE
Build error in Colab

### ISSUE THREAD

**Issue by jsilbergDS** [kpu/kenlm#338]
From working directory of kenlm, I am running: 

!cmake .
!make -j 4
!ls

And getting: 

-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   system
--   thread
--   unit_test_framework
--   chrono
--   date_time
--   atomic
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at CMakeLists.txt:115 (install):
  install TARGETS given target "kenlm" which does not exist in this
  directory.

-- Configuring incomplete, errors occurred!
See also "/content/OpenSeq2Seq/decoders/kenlm/CMakeFiles/CMakeOutput.log".
See also "/content/OpenSeq2Seq/decoders/kenlm/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
build		     CMakeFiles		    COPYING.LESSER.3   MANIFEST.in
BUILDING	     CMakeLists.txt	    Doxyfile	       python
clean_query_only.sh  compile_query_only.sh  kenlmConfig.cmake  README.md
cmake		     COPYING		    LICENSE	       setup.py
CMakeCache.txt	     COPYING.3		    lm		       util

Any ideas? I have tried uninstalling and reinstalling cmake using apt, but the version still says 3.10. Thanks for building this!!

**Comment by kpu** [comment]
Does commit 0c4dd4e8a29a9bcaf22d971a83f4974f1a16d6d9 work?  cc @jacobkahn

**Comment by jacobkahn** [comment]
@jsilbergDS a newer version of CMake might solve the issue. Either way, I'll take a look soon.

**Comment by kpu** [comment]
Thanks!  Let's consolidate in #336 since this seems to be a duplicate.
