### ISSUE TITLE
Question about model interpolation

### ISSUE THREAD

**Issue by darksurfer** [kpu/kenlm#34]
Hello, 
I know this isn't an issue but I didn't found anywhere else to ask. 
I think there is no way ton interpolate plural arpa models into one as the SRILM and IRSTLM does.  Is this a features planned or kenlm don't do it on purpose ?

Thank you anyway for the awesome job with kenlm !

**Comment by kpu** [comment]
We're actively working on interpolation and you can watch the lm/interpolate directory.  It's not ready yet though.

**Comment by lingz** [comment]
I'm wondering what the state of interpolation is? Is it ready for use?

**Comment by kpu** [comment]
Log-linear It's implemented per http://kheafield.com/professional/edinburgh/interpolate_paper.pdf .  You'll need to compile with Eigen then run the interpolate program for help.
