### ISSUE TITLE
installing KenLM

### ISSUE THREAD

**Issue by CapitalChi** [kpu/kenlm#35]
Running on OSX, boost 1.55
I'm essentially following the instructions in this document: 
http://victor.chahuneau.fr/notes/2012/07/03/kenlm.html

Interestingly, everything worked once, but then stopped working.  When I input ./bjam, I get a couple of errors, one involving a broken pipe, but the one I'm most concerned about is:

-bash: ./kenlm/bin/lmplz: No such file or directory

The output begins with: warning: No toolsets are configured.
warning: Configuring default toolset "darwin".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
...patience...
...found 628 targets...
...updating 38 targets...
 
and at the end, the output is...

...failed darwin.link lm/bin/left_test.test/darwin-5.1.0/release/threading-multi/left_test...
...skipped <plm/bin/left_test.test/darwin-5.1.0/release/threading-multi>left_test.run for lack of <plm/bin/left_test.test/darwin-5.1.0/release/threading-multi>left_test...
...failed updating 23 targets...
...skipped 15 targets...

If I could attach the log I would but it's very long!

**Comment by kpu** [comment]
Can't do anything without the log.  kenlm@kheafield.com

**Comment by CapitalChi** [comment]
Hi,
Thanks for taking a look.  I didn’t see an attachment feature on the github page.
Rachel

**Comment by kpu** [comment]
Thanks for the log Rachel!

It looks like the code is being compiled as C++11 but being linked as C++98?  For example, the code is looking for C++11 libraries but not finding them:

Undefined symbols for architecture x86_64:
  "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)",

Does your CFLAGS or CXXFLAGS contain "-std=c++11" ?  Things to try:
1. LDFLAGS="-std=c++11" and rerun
or
2. Pure C++98: remove -std=c++11 from the CFLAGS and CXXFLAGS.

**Comment by kpu** [comment]
Are you compiling this within Moses or from github.com/kpu/kenlm?  Moses recently turned C++11 on, but the kenlm git repo uses C++98 by default.  You can also email me directly at kenlm@kheafield.com.

**Comment by hieuhoang** [comment]
you might also want to compile with the following argument
   toolset=clang
I've successfully compiled, the only things that breaks are the unit test, due to linking issues that have been seen in moses before. This is my exact command
   ./bjam --with-boost=/Users/hieu/workspace/boost/boost_1_56_0.clang/ -j4 toolset=clang  
....
lm/bin/left_test.test/clang-darwin-4.2.1/release/link-static/threading-multi/left_test
ld: warning: directory not found for option '-L/Users/hieu/workspace/boost/boost_1_56_0.clang/lib'
Undefined symbols for architecture x86_64:
  "boost::unit_test::unit_test_main(bool (*)(), int, char**)", referenced from:
      _main in left_test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
......

**Comment by dowobeha** [comment]
The current kenlm master compiles cleanly (all unit tests pass) for me on Mac OS X 10.10.3 Yosemite, using boost 1.58 (installed using fink) with the command ./bjam --with-boost=/sw/opt/boost-1_58. 

My g++ --version returns the following:
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

What versions of Mac OS X and g++ are you using?

**Comment by kpu** [comment]
Looks like clang 5.1.0?

**Comment by CapitalChi** [comment]
Hi everyone, sorry for not responding earlier, and I am very happy that you are taking the time to respond.  Let me try your suggestions now.

**Comment by CapitalChi** [comment]
Also, I am compiling from github.com/kpu/kenlm, not using moses.

**Comment by CapitalChi** [comment]
My g++ --version gives me: 
 g++ (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.

Mac OSX Yosemite 10.10.3

**Comment by kpu** [comment]
Oh, real gcc on OS X.  Try adding the argument toolset=gcc ?  Still confused as to why it's doing C++11 stuff though.  Does a simple C++ program that uses std::string compile and link with -std=c++11?

**Comment by hieuhoang** [comment]
did u install gcc yourself? imo, it's a bad idea unless you're willing to deal with library/header issues like this. you're on a mac, use clang, get over it

**Comment by CapitalChi** [comment]
Hi everyone, just adding -toolset=clang did the trick for compiling.  (I got over it; used Clang :) )

The only error that seems to remain now is importing kenlm in Python.
>>> import kenlm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/jir955/klm/lib/python2.7/site-packages/kenlm.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /Users/jir955/klm/lib/python2.7/site-packages/kenlm.so
  Expected in: dynamic lookup

Any ideas?

**Comment by CapitalChi** [comment]
(Also, again, thanks for your help.)

**Comment by CapitalChi** [comment]
Python 2.7.9 |Anaconda 2.2.0 (x86_64)|

**Comment by kpu** [comment]
Looks like gcc being used to compile the python library?  Try taking the setup.py commands and substituting clang.

**Comment by CapitalChi** [comment]
Hi Ken,
I've tried modifying the setup.py file in various ways (below)-- for example, setting up an environment, adding extra compiling arguments, doing both at the same time,  everything I can think of.  Also tried adding export CC=clang to my bashrc file.  All of these produce the same error as before.  I did check that the kenlm.so file exists. 

Just to be clear, lmplz does work to produce an arpa file.  It's the import kenlm that doesn't work (i.e. the python module).
Also, I brew uninstalled gcc in case that was causing the problem.

setup.py:

from distutils.core import setup
from distutils.extension import Extension
import glob
import platform
import os

os.environ["CC"] = "/usr/bin/clang"
os.environ["CXX"] = "/usr/bin/clang"

FILES = glob.glob('util/*.cc') + glob.glob('lm/*.cc') + glob.glob('util/double-conversion/*.cc')
FILES = [fn for fn in FILES if not (fn.endswith('main.cc') or fn.endswith('test.cc'))]

LIBS = ['z', 'stdc++']
if platform.system() != 'Darwin':
    LIBS.append('rt')

ext_modules = [
    Extension(name='kenlm',
        sources=FILES + ['python/kenlm.cpp'],
        language='C++', 
        include_dirs=['.'],
        libraries=LIBS, 
        extra_compile_args=['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6','-toolset=/usr/bin/clang'])
]

setup(
    name='kenlm',
    ext_modules=ext_modules
)

**Comment by CapitalChi** [comment]
Hi, thank you for your help so far.  With nm kenlm.so, a small excerpt of what I get is
0000000000072a60 S __ZTIN4util9ExceptionE
U __ZTINSt8ios_base7failureB5cxx11E
U __ZTISt11range_error
So, am I interpreting it correctly to say that the symbol is undefined and will be looked up in the c++11 library?

**Comment by kpu** [comment]
To be honest, you've exceeded my knowledge.  I am still confused as to why the .so file is being compiled with C++11 symbol dependencies.  Do you happen to know what library has those C++ symbols?

**Comment by hieuhoang** [comment]
i personally don't know, i've never used the python bindings. From the error, it looks like clang/gcc problems again. I would recompile everything that u had previously compiled with gcc.

also, CXX should prob be set to clang++

**Comment by CapitalChi** [comment]
By looking through my history I was able to find where the problems started; when I was trying to install the MIT lm I followed this article https://groups.google.com/forum/#!topic/stacks-users/h2aIng0PMnA
"
2) delete the old compiler 
type in the terminal : 
which gcc 
Should be in /usr/bin
In Finder : cmd-shift-g or in menu bar: Go->Go to Folder then type /usr/bin
Find and delete: cpp, g++, gcc, gcov

3) Install the new gcc (gcc-4.9-bin.tar.gz) from : http://hpc.sourceforge.net
in Terminal move to Download directory: cd Downloads
and type
sudo tar -xvf gcc-4.9-bin.tar -C/
"

**Comment by hieuhoang** [comment]
what's the pros and cons of MIT LM over irstlm or kenlm?

**Comment by CapitalChi** [comment]
There were no pros-- I am trying to building a language model, and I came across the MIT one first.  However there are major issues that have come up in the MIT LM as new versions of XCode have come out that MIT LM hasn't resolved by updating itself

**Comment by kpu** [comment]
So is this resolved by unborking the compiler?  I'm also confused as to how you got gcc 5 by doing sudo tar -xvf gcc-4.9-bin.tar .

**Comment by CapitalChi** [comment]
I changed it to the most recent version. Anyway I think something that might have worked is deleting usr/local and reinstalling Xcode. But before doing that I just decided to give in the computer to be reimaged. I have learned a valuable lesson :)



Sent with Good (www.good.com)


-----Original Message-----

**Comment by CapitalChi** [comment]
Hi again :)
I am now starting from square 1 again, with another error.  This problem is also occurring for my colleague who tried to install kenlm with me a few days ago.  We both brew installed boost (and boost-python).  When we run ./bjam, we get the error


Failed to run bash -c "g++  -dM -x c++ -E /dev/null -include boost/version.hpp 2>/dev/null |grep '#define BOOST_'"

Boost does not seem to be installed or g++ is confused.

After googling, I see that some Moses users encountered this for various reasons, but that makes sense to the extent that it is the same code;  I looked around and this is coming from the sanity.jam file:
#Argument is e.g. 103600
rule boost ( min-version ) {
  local cmd = "bash -c \"g++ "$(I-boost-include)" -dM -x c++ -E /dev/null -include boost/version.hpp 2>/dev/null |grep '#define BOOST_'\"" ;
  local boost-shell = [ SHELL "$(cmd)" : exit-status ] ;
  if $(boost-shell[2]) != 0 && $(CLEANING) = no {
    echo Failed to run "$(cmd)" ;
    exit Boost does not seem to be installed or g++ is confused. : 1 ;
  }

I tried to see what this would give me: g++ -x c++ -E /dev/null -include boost/version.hpp -v


Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)

Target: x86_64-apple-darwin14.3.0

Thread model: posix

 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.10.0 -E -disable-free -disable-llvm-verifier -main-file-name null -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 242 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0 -include boost/version.hpp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/jir955/kenlm -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ /dev/null

clang -cc1 version 6.1.0 based upon LLVM 3.6.0svn default target x86_64-apple-darwin14.3.0

ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/v1"

ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/local/include"

ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/Library/Frameworks"

#include "..." search starts here:

#include <...> search starts here:

 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1

 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/include

 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include

 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include

 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks (framework directory)

End of search list.

# 1 "/dev/null"

# 1 "<built-in>" 1

# 1 "<built-in>" 3

# 326 "<built-in>" 3

# 1 "<command line>" 1

In file included from <built-in>:326:

<command line>:1:10: fatal error: 'boost/version.hpp' file not found

#include "boost/version.hpp"

         ^

# 1 "<built-in>" 2

# 1 "/dev/null" 2


1 error generated.


Thank you for your help.
Best wishes,
Rachel

**Comment by kpu** [comment]
Where is Boost installed?  You can use --with-boost=/path/to/installation to specify a non-standard path.

**Comment by CapitalChi** [comment]
Boost is installed in /usr/local/Cellar. That is where homebrew is placing what I brew install.  Although new to this all I thought that path issues were dealt with by modifying /etc/paths or alternatively adding PATH=/usr/local/bin:$PATH to the .bashrc file.  When I echo $PATH I get:

/usr/local/bin/:/usr/local/Cellar:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/jir955/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Is this not what you meant? To which command do you suggest appending --with-boost=/path/to/installation? Thank you.

**Comment by kpu** [comment]
bjam --with-boost=/usr/local/Cellar

PATH impacts running executables.  There are other environment variables for include directories etc.  See http://kheafield.com/code/kenlm/dependencies/

#Determine where you want to install packages
PREFIX=/usr/local/Cellar
#If your system has lib64 directories, lib64 should be used instead of lib
if [ -d /lib64 ]; then
  LIBDIR=$PREFIX/lib64
else
  LIBDIR=$PREFIX/lib
fi
#If you're installing to a non-standard path, tell programs where to find things:
export PATH=$PREFIX/bin${PATH:+:$PATH}
export CPATH=$PREFIX/include${CPATH:+:$CPATH}
export LIBRARY_PATH=$LIBDIR${LIBRARY_PATH:+:$LIBRARY_PATH}
if [ "$(uname)" == Darwin ]; then
  export DYLD_LIBRARY_PATH=$LIBDIR${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}
else
  export LD_LIBRARY_PATH=$LIBDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi

**Comment by CapitalChi** [comment]
Hello, thanks for the response.  I tried these things and am still ending up with the same error message, i.e. Failed to run bash -c "g++ -I/usr/local/Cellar/include -dM -x c++ -E /dev/null -include boost/version.hpp 2>/dev/null |grep '#define BOOST_'"
Boost does not seem to be installed or g++ is confused.

**Comment by kpu** [comment]
You should get this command to run successfully (i.e. print SUCCESS).  
g++ -I/usr/local/Cellar/include -x c++ -E /dev/null -include boost/version.hpp && echo SUCCESS
Until then, it's really between you, the compiler, and Boost.

**Comment by CapitalChi** [comment]
Yep, not yet. I'll work on it some more. 
98e0d9879a43:kenlm jir955$ g++ -I/usr/local/Cellar/include -x c++ -E /dev/null -include boost/version.hpp && echo SUCCESS
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 326 "<built-in>" 3
# 1 "<command line>" 1
In file included from <built-in>:326:
<command line>:1:10: fatal error: 'boost/version.hpp' file not found
#include "boost/version.hpp"
         ^
# 1 "<built-in>" 2
# 1 "/dev/null" 2

1 error generated.

**Comment by CapitalChi** [comment]
Hey, it should be just -I/usr/local/include.  In that case, I get success:
98e0d9879a43:kenlm jir955$ g++ -I/usr/local/include -x c++ -E /dev/null -include boost/version.hpp && echo SUCCESS
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 326 "<built-in>" 3
# 1 "<command line>" 1
# 1 "/usr/local/include/boost/version.hpp" 1
# 2 "<command line>" 2
# 1 "<built-in>" 2
# 1 "/dev/null" 2

SUCCESS

**Comment by CapitalChi** [comment]
Hi, modifying Ken's earlier suggestion I now can compile with the following:  ./bjam --with-boost=/usr/local/
However, at the next step, python setup.py install, I get the following:
98e0d9879a43:kenlm jir955$ python setup.py install
running install
running build
running build_ext
building 'kenlm' extension
creating build
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/util
creating build/temp.macosx-10.5-x86_64-2.7/lm
creating build/temp.macosx-10.5-x86_64-2.7/util/double-conversion
creating build/temp.macosx-10.5-x86_64-2.7/python
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/bit_packing.cc -o build/temp.macosx-10.5-x86_64-2.7/util/bit_packing.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/ersatz_progress.cc -o build/temp.macosx-10.5-x86_64-2.7/util/ersatz_progress.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/exception.cc -o build/temp.macosx-10.5-x86_64-2.7/util/exception.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/file.cc -o build/temp.macosx-10.5-x86_64-2.7/util/file.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/file_piece.cc -o build/temp.macosx-10.5-x86_64-2.7/util/file_piece.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/mmap.cc -o build/temp.macosx-10.5-x86_64-2.7/util/mmap.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/murmur_hash.cc -o build/temp.macosx-10.5-x86_64-2.7/util/murmur_hash.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/parallel_read.cc -o build/temp.macosx-10.5-x86_64-2.7/util/parallel_read.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/pool.cc -o build/temp.macosx-10.5-x86_64-2.7/util/pool.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/read_compressed.cc -o build/temp.macosx-10.5-x86_64-2.7/util/read_compressed.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/scoped.cc -o build/temp.macosx-10.5-x86_64-2.7/util/scoped.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/string_piece.cc -o build/temp.macosx-10.5-x86_64-2.7/util/string_piece.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c util/usage.cc -o build/temp.macosx-10.5-x86_64-2.7/util/usage.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c lm/bhiksha.cc -o build/temp.macosx-10.5-x86_64-2.7/lm/bhiksha.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c lm/binary_format.cc -o build/temp.macosx-10.5-x86_64-2.7/lm/binary_format.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c lm/config.cc -o build/temp.macosx-10.5-x86_64-2.7/lm/config.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c lm/lm_exception.cc -o build/temp.macosx-10.5-x86_64-2.7/lm/lm_exception.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
gcc -fno-strict-aliasing -I/Users/jir955/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -I/Users/jir955/anaconda/include/python2.7 -c lm/model.cc -o build/temp.macosx-10.5-x86_64-2.7/lm/model.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -DHAVE_ZLIB -DHAVE_BZLIB
In file included from lm/model.cc:1:
In file included from ./lm/model.hh:13:
In file included from ./lm/vocab.hh:7:
./util/fake_ofstream.hh:15:10: fatal error: 'boost/lexical_cast.hpp' file not
      found
#include <boost/lexical_cast.hpp>
         ^
1 error generated.
error: command 'gcc' failed with exit status

**Comment by CapitalChi** [comment]
And this was fixed by modifying in bashrc PREFIX=/usr/local/  :)

**Comment by kpu** [comment]
Is this resolved?   In return, I'd like a Capital One UK account opened on the basis of my existing Capital One US relationship and credit score.

**Comment by CapitalChi** [comment]
Hahah. I myself haven't been able to get a card, because of lack of credit history, even though I now work there and even though they have sent me many pre-approved offers.  And I'm planning to send you a personal little gift to your academic address of some kind, since you have helped out a poor soul like me.  
I believe it works, it just scored a sentence! So I am closing this :)
