### ISSUE TITLE
covert .arps to .klm  error

### ISSUE THREAD

**Issue by Deep-sea-boy** [kpu/kenlm#353]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/37582640/132122464-01e355f6-ef8e-4d14-9e8e-90b3b35932e6.png">

help!!!!!!!

**Comment by Deep-sea-boy** [comment]
I have tried the small file of 200M is ok. Is it possible that the conversion fails because the file is too large

**Comment by Deep-sea-boy** [comment]
myfile:   pdf_content_text:22G  >  pdf_arps:4.7G  >  (error_build for .klm)

**Comment by kpu** [comment]
You ran out of RAM.  Get more RAM or read https://kheafield.com/code/kenlm/structures/
