### ISSUE TITLE
is it possible to get the next words distribution using kenlm?

### ISSUE THREAD

**Issue by SatenHarutyunyan** [kpu/kenlm#367]
We have a  trained language model but we only can get the probability of a sentence, but we want to have the distribution of the next word probabilities given the previous n-1 words.
We can do it with python like this: 
for token in all_tokens:
    prob(token) = prob(sentence+token) / prob(sentence)

and then take the token with maximum probability. We are wondering if there is a method that does all this with c++ and we can avoid the for loop.
thank you

**Comment by kpu** [comment]
The data structure was not setup to efficiently perform a query of all words given a context.  As a reverse trie, the first word looked up is the word being predicted, so it still has to look up every word then follow the path back for context.  

So for better or worse the most efficient query method is making a `State` object and using it to predict all the next words in a C++ for loop.  

IRSTLM has a data structure setup to make this query efficient but I am not sure they actually have an API to do it.
