### ISSUE TITLE
How to install successfully compiled windows binaries to python?

### ISSUE THREAD

**Issue by orrburgel** [kpu/kenlm#368]
I don't get something, I downloaded visual studio 2010 professional and successfully built the project with the following kenlm build: https://github.com/kpu/kenlm/archive/windows.zip in release x64.

Now I'm kind of stuck not knowing how to import the package in python, I ended up with a working `kenlm_build_binary_x64.exe` file but how do I install it with pip so I can run `import kenlm` without getting `ModuleNotFoundError: No module named 'kenlm'`?

Thanks a lot for any help! Really!

**Comment by kpu** [comment]
You need to compile the python library using https://github.com/kpu/kenlm/blob/master/setup.py

**Comment by orrburgel** [comment]
downgrading to python 3.9 and using this worked:
pip install kenlm-cygwin

**Comment by orrburgel** [comment]
I'm so close to build this thing for windows, getting: `fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory`
Anyone knows maybe how to fix this? py3.7

**Comment by orrburgel** [comment]
What python version I need to run this on windows? I tried 3.10 3.9 3.8 3.7 and 3.6

**Comment by kpu** [comment]
The install zlib.

**Comment by orrburgel** [comment]
I have zlib installed in a billion ways before I submitted my problem

**Comment by orrburgel** [comment]
should I reopen a new issue? @kpu
