### ISSUE TITLE
Missing documentation for base of log probabilities

### ISSUE THREAD

**Issue by arvoelke** [kpu/kenlm#38]
Hello. Firstly thanks for this great tool. The Python support has made this very easy to use alongside `nltk` for some recent research.

I'm having difficulty finding documentation for the probabilities from `model.full_scores()`. They appear to be log probabilities, but I'm unsure of which base?

Scanning through the repository, I found this line that seems to indicate that it is base 10: https://github.com/kpu/kenlm/blob/a8a1b55be3d9e07e670e473e5777892b2fdbeb3e/lm/wrappers/nplm.cc#L67

But I can't find any other reason to confirm that this is the case. Thanks.

**Comment by kpuatwork** [comment]
It is in fact log10 for historical reasons and compatibility with other 
toolkits.  Generally, I guess I could do more to explain how LMs work at 
a high level.

**Comment by arvoelke** [comment]
Great! Thanks for the quick confirmation.
