### ISSUE TITLE
Please update double-conversion/utils.h

### ISSUE THREAD

**Issue by HougeLangley** [kpu/kenlm#386]
Missing __loongarch__ 

Google version have been added.

https://github.com/google/double-conversion/blob/master/double-conversion/utils.h#L135

**Comment by kpu** [comment]
I've updated it, reopen if there's still a problem.

**Comment by HougeLangley** [comment]
I have been test, success in my Gentoo

**Comment by HougeLangley** [comment]
haive been fixed https://github.com/fcitx/libime/issues/32
