### ISSUE TITLE
(Document Classification) How to get a document score with KenLM?

### ISSUE THREAD

**Issue by piegu** [kpu/kenlm#389]
Hi @kpu,

Many thanks for your work! 
I would like to use KenLM for Document Classification (I have the text files of documents and the documents belong to 10 categories).

My idea is to train by category a KenLM model (10, here) and then, score a new document through the 10 KenLM models.
Thus, the "best" score will give the category of the document.

My question is: what would be this "document score" and how to calculate it from the text file of a document?

**Comment by kpu** [comment]
Sentences are independent.  You probably want perplexity per word https://en.wikipedia.org/wiki/Perplexity computed from the 10 models.  Note that, especially if training data size is unbalanced, you will want to tune thresholds rather than simply take the lowest perplexity per word.

**Comment by piegu** [comment]
> You probably want perplexity per word computed from the 10 models

Thank you for your answer but I don't know how to apply it in practice.
What is the KenLM code you would use?

This following one?

```
import numpy as np
import kenlm

m1 = kenlm.Model('kenlm_model1.arpa')
m2 = kenlm.Model('kenlm_model2.arpa')

# text with 2 sentences
text = "My idea is to train by category a KenLM model (10, here) and then, score a new document through the 10 KenLM models. Thus, the "best" score will give the category of the document."

ppl1 = m1.perplexity(text)
ppl2 = m2.perplexity(text)

if ppl1 <= ppl2:
   print("the text class is 1")
else:
  print("the text class is 2")
```
