### ISSUE TITLE
internal complie error

### ISSUE THREAD

**Issue by hexists** [kpu/kenlm#40]
Hi ~ I has some issue when I tried to compile **mosesdecoder** on RedHat 5.8 & gcc 4.1.2.
Any tip how to fix it?
Thank you very much!

```
./util/scoped.hh:70: internal compiler error: in build_call, at cp/call.c:321
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccnex5v6.out file, please attach this to your bugreport.
...failed gcc.compile.c++ lm/bin/gcc-4.1.2/release/debug-symbols-on/link-static/threading-multi/quantize.o...
```

**Comment by kpu** [comment]
As noted in the error message, this is a bug in the ancient compiler you are using.  If you must use RedHat Stale Linux, please file the bug report with them as instructed in the error message.

**Comment by hexists** [comment]
Thank you.
