### ISSUE TITLE
How sentences are tokenized?

### ISSUE THREAD

**Issue by MagedSaeed** [kpu/kenlm#407]
Thanks for the great software.

Just a question to tokenize my text accordingly, how the sentence markers are added _internally_ as mentioned in the docs? Are they added by splits of \n?

**Comment by kpu** [comment]
`lmplz` and `query` treat '\n' in the data as a sentence split.  A sentence split implicitly conditions on `<s>` and appends `</s>`.

**Comment by MagedSaeed** [comment]
Thanks for your reply @kpu
