### ISSUE TITLE
cppcheck

### ISSUE THREAD

**Issue by IgorPolyakov** [kpu/kenlm#49]
Hello! I'm new in open source, and like to help)
I check [kenlm](https://github.com/kpu/kenlm) project on Cppcheck. Cppcheck is a static analysis tool for C/C++ code.
All error linked to "jam-files/engine". Can I fix these errors over pull request? 
Or it is not used the code?

[jam-files/engine/compile.c:69]: (error) Buffer is accessed out of bounds.
[jam-files/engine/hcache.c:146]: (error) Common realloc mistake: 'buf' nulled but not freed upon failure
[jam-files/engine/lists.c:104]: (error) Pointer to local array variable returned.
[jam-files/engine/lists.c:135]: (error) Pointer to local array variable returned.
[jam-files/engine/lists.c:35]: (error) Allocation with malloc, return doesnt release it.
[jam-files/engine/make1.c:121]: (error) Allocation with malloc, return doesnt release it.
[jam-files/engine/mkjambase.c:73]: (error) Resource leak: fout
[jam-files/engine/modules/order.c:85]: (error) Memory leak: colors
[jam-files/engine/object.c:262]: (error) Memory leak: m
[jam-files/engine/regexp.c:255]: (error) Memory leak: r
[jam-files/engine/regexp.c:520]: (error) Uninitialized variable: classend
[jam-files/engine/regexp.c:521]: (error) Uninitialized variable: classr
[jam-files/engine/rules.c:552]: (error) Buffer is accessed out of bounds.
[jam-files/engine/yyacc.c:166]: (error) Memory leak: key.string
[jam-files/engine/yyacc.c:195]: (error) Resource leak: grammar_source_f

full list: http://pastebin.com/0AjCPcD

**Comment by kpu** [comment]
That's just the build system, not my code.  File a bug upstream: http://www.boost.org/build/.

**Comment by IgorPolyakov** [comment]
ok) thanks
