### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by brunoalano** [kpu/kenlm#50]
It's possible to upload the official repo into PyPI?

**Comment by kpu** [comment]
Slowly learning how PyPI works...

**Comment by riyadparvez** [comment]
+1

**Comment by rmsmith88** [comment]
any update on this? i get errors installing it the current recommended way. Will open new issue

**Comment by kpu** [comment]
https://pypi.python.org/pypi?name=kenlm&version=0.0.0&:action=display
