### ISSUE TITLE
lack of basic functionality

### ISSUE THREAD

**Issue by xuancong84** [kpu/kenlm#52]
Even the most basic function P(you | where are) cannot be computed,
full_scores("where are you") automatically append "\<s\>" at the beginning of the phrase which is stupid.
If I really want to compute "\<s\> where are you", I will append "\<s\>" by myself.

**Comment by kpu** [comment]
The python function is
def full_scores(self, sentence, bos = True, eos = True)
Guess what the bos and eos parameters do.  
Also, appending <s> is generally incorrect since it is implicit context, not a word to be queried.
