### ISSUE TITLE
Parsing ngrams as it is.

### ISSUE THREAD

**Issue by znavoyan** [kpu/kenlm#53]
Hello, in the kenlm documents I found only one function to use:   en_model.score(sentence).
Can you please provide detail description of functions available if there are?
I'm trying to parse unigram, birgram trigram probabilities from LM as they appear there.
For example LM contain the following lines. I need to have a function which will work like this: en_model.bigram_prob("too recognize") will return -4.923469
-4.923469	too recognised
-4.923469	too recognises
-4.923469	too recognize
-4.923469	too recommend
The same for unigrams and trigrams.

Does kenlm support such functionality ?

Thank you,
Zaven.

**Comment by kpu** [comment]
Read [python/example.py](python/example.py) and [python/kenlm.pyx](python/kenlm.pyx).  I admit the docs should link there.

**Comment by kpu** [comment]
Is there a class assignment going on?  I've gotten e-mails from three people asking for the same functionality, all in the Python API.  It's there, I'll write better docs some point.

**Comment by znavoyan** [comment]
Thank you for the reply. I have seen example.py and tried to implement the feature using full_scores(...). Which worked for me, only when set additional two parameter's values to false full_scores(ngram, False, False)
