### ISSUE TITLE
Feature: Build KenLM model from n-gram counts file

### ISSUE THREAD

**Issue by Tooa** [kpu/kenlm#55]
Hi :wave: , 

it would be nice to learn language models on existing count files that contain n-gram counts. Similar to the `ngram-count` parameter `-read` from [`SRILM`](http://www.speech.sri.com/projects/srilm/manpages/ngram-count.1.html). The ability to only load those counts, enables the use of essentially unlimited n-gram statistics like skip-ngram.

**Comment by kpu** [comment]
The downstream algorithms assume that every substring of a n-gram is an n-gram.  Do your use cases ensure that property?

**Comment by manishbansal-fk** [comment]
@Tooa Would repeating by count help here ?

**Comment by Tooa** [comment]
Closing this issue as it is not relevant to me anymore.
