### ISSUE TITLE
equivalent to hidden-ngram

### ISSUE THREAD

**Issue by vince62s** [kpu/kenlm#60]
Hi Ken,

Is there a way to replicate with KenLM the workflow where we can build a LM as with the continuous-ngram-count and then query/process a text with hidden-ngram (given an hidden-vocab file) ?

Cheers,
Vince

**Comment by kpu** [comment]
lmplz efficiently handles very very long lines.  So for continuous-ngram-count you can just strip out the newlines in the training data.  

Regarding hidden-ngram, that's a special case of hypergraph decoding, which is in https://github.com/kpu/lazy .  A utility on top of hypergraph decoding would be welcome.
