### ISSUE TITLE
Converting files from ARPA format to KenLM's "--intermediate" format

### ISSUE THREAD

**Issue by lallubharteja** [kpu/kenlm#62]
Hi,

Is there a tool to convert existing ARPA format files to files as generated by lmplz's --intermediate flag ?

Thanks Mittul

**Comment by kpu** [comment]
No.  It's possibly to write one, but ultimately I want to kill off the intermediate format and make the interpolate tool read from the trie format.

**Comment by lallubharteja** [comment]
ok. closing this issue then !
