### ISSUE TITLE
Perplexity evaluated on full documents or full sentence?

### ISSUE THREAD

**Issue by windweller** [kpu/kenlm#69]
Sorry about this question :(

I ran into some confusion that I always thought perplexity for a document is evaluated per sentence, then you do the average for all the sentences' perplexities in the document. Is this how KenLM implemented bin/query?

Or did KenLM evaluate the perplexity on the whole documents then normalize it by the length of the document?

**Comment by kpu** [comment]
It's evaluated on whole documents then normalized by length, in words, of the document.
