### ISSUE TITLE
words distribution about language model

### ISSUE THREAD

**Issue by zhang-wen** [kpu/kenlm#73]
here i have a question about KenLM, i want to use following function:
	assume i have a trained 3-gram language model, i want to 
get probabilities of all words in vocabulary given a two-words sequence,
say, i have a two-words sequence "A B".
i want to get:
`P(A|A B)  P(B|A B)  P(C|A B)  P(D|A B)  P(E|A B) ` and so on
does c++ or python provide this interface ? thanks a lot.

**Comment by kpu** [comment]
Not efficiently.  The data structures are primarily keyed by the word being predicted.  You can do a for loop against a State object.  To do this efficiently you'd need a different data structure, typically a forward trie.

**Comment by zhang-wen** [comment]
thank you very much.
what do you mean by "the word being predicted", you mean the words that have been seen in the training data? not words in the whole vocabulary ?
