### ISSUE TITLE
Different scores for 4-gram and 5-gram LM on sentence whose length is 4

### ISSUE THREAD

**Issue by zhang-wen** [kpu/kenlm#74]
hi @kpu  i have a question for you.

i train a 4-gram lm and a 5-gram lm on same corpus with the same configuration.

when i test the language model on a sentence, i found an unreasonable result:

for example, i have a sentence here:

```
m4 = kenlm.Model('4gram-lm')
m5 = kenlm.Model('5gram-lm')
sent_3 = 'bolivia holds presidential'
s4 = m4.score(sent_3, bos = False, eos = False)
s5 = m5.score(sent_3, bos = False, eos = False)
```
i test the language model score on a sentence whose length is 3, i got exactly same s4 and s5 which is reasonable.

```
s4: -13.948734283447266
s5: -13.948734283447266
```

but when i test on a sentence whose length is 4, strange thing happens:

```
sent_4 = 'bolivia holds presidential and'
s4 = m4.score(sent_4, bos = False, eos = False)
s5 = m5.score(sent_4, bos = False, eos = False)
```

```
s4: -8.61363410949707
s5: -8.647890090942383
```
i think, s4 and s5 should be same, as we can see, however, i got a little different s4 and s5 there:
because for string the length of which is 4, do not consider bos and eos
```
p4(w1 w2 w3 w4) = p(w1) * p(w2 | w1) * p(w3 | w1 w2) * p(w4 | w1 w2 w3)
p5(w1 w2 w3 w4) = p(w1) * p(w2 | w1) * p(w3 | w1 w2) * p(w4 | w1 w2 w3)
```
so p4 and p5 should be the same , right ? can you give me some explanations about this ?

of cause, for sentence whose length is 5, it will be different, because last items in following formula are different.
```
p4(w1 w2 w3 w4 w5) = p(w1) * p(w2 | w1) * p(w3 | w1 w2) * p(w4 | w1 w2 w3) * p(w5 | w2 w3 w4)
p5(w1 w2 w3 w4 w5) = p(w1) * p(w2 | w1) * p(w3 | w1 w2) * p(w4 | w1 w2 w3) * p(w5 | w1 w2 w3 w4)
```

**Comment by kpu** [comment]
Probabilities are based on adjusted counts.  For highest order these are the same.  For lower orders, these are the number of unique extensions to the right.  
So a 4-gram in a 4-gram LM bases on actual counts, but a 4-gram in a 5-gram LM bases on number of unique extensions to the right.
