### ISSUE TITLE
Using KenLM with ngram order greater than 6

### ISSUE THREAD

**Issue by saatvikshah1994** [kpu/kenlm#75]
I rebuilt my kenlm with max order set to 10 by using:
` cmake .. -DKENLM_MAX_ORDER=10`
during the build process
, while building, and by updating the setup.py file: 
`ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=10']`.

Now, I'm able to use lmplz without an error to build a 7 gram Language model.

However, when trying to use the python interface, I still get the following error:

> IOError: Cannot read model '../models/LM_7gram.klm' (lm/model.cc:49 in void lm::ngram::detail::(anonymous namespace)::CheckCounts(const std::vector<uint64_t> &) threw FormatLoadException because `counts.size() > 6'. This model has order 7 but KenLM was compiled to support up to 6.  If your build system supports changing KENLM_MAX_ORDER, change it there and recompile.  In the KenLM tarball or Moses, use e.g. `bjam --max-kenlm-order=6 -a'.  Otherwise, edit lm/max_order.hh.)

**Comment by saatvikshah1994** [comment]
Sorry, it was a python path related error, the above steps should work correctly.

**Comment by HJJ256** [comment]
> Sorry, it was a python path related error, the above steps should work correctly.

Hey @saatvikshah1994, after recompiling the bindings, did it work for you, because I keep getting segmentation fault and malloc errors during inference after upgrading kenlm with  -DKENLM_MAX_ORDER=10 and then rebuilding the python library

Any help would be appreciated
