### ISSUE TITLE
supports for Language Model Rest Costs feature ?

### ISSUE THREAD

**Issue by timotheev** [kpu/kenlm#76]
Hi,
Thank you for those nice pieces of code !
I am discovering LM, playing around with various corpus... I recently read the article about better estimation (http://kheafield.com/professional/edinburgh/rest_paper.pdf), training N n-gram models instead of one with equal discounts values at each order for interpolation and BoW, generating a file with entries:
n-gram Pn PN(n) BN(n)
instead of the classic ARPA entries:
n-gram PN(n) BN(n)
To use Max-likelihood estimates when context is missing instead of never-encountered (uncomplete left states).

1/ Is this a behavior already implemented as part of the kenLM code but undocumented so far in the estimation section ? (It would make no sens to execute lpmz and read that many times the input file to get N models...)

2/ I though I could use --discount_fallback to force lower order models use the higher order discounts rather than the Chen & Goodman estimation that differs when context/occurrence counts are used, but as it is just a fallback is does not work... Is there any work-around ?

(also I don't fully understand the discount_fallback option usage I guess... Using: 
"~$./build/bin/lmplz -o 3 -S 50% -T /tmp discount_fallback=0.5 1 1.5  <LMinput.txt >LMoutpu.arpa"
for the following dummy input text:
"A A A A A A A A A A A A A A A A A A A A A"
(I know it is the default values, this just to test...) I get:
"Substituting fallback discounts for order 0: D1=0.5 D2=0.5 D3+=0.5"
in stderr).

Thanks

**Comment by kpu** [comment]
The procedure for rest costs is to run lmplz in a for loop to generate N different models with different orders.  Then build binary with the lower ones as arguments to -r (for rest).
```bash
for ((i=1;i<5;++i)); do
  lmplz -o $i -S 50% -T /tmp <LMinput.txt >$i.arpa
done
build_binary -r "1.arpa 2.arpa 3.arpa 4.arpa" 5.arpa 5.probing
```

`discount_fallback` is for the unrelated case where discounts can't be properly estimated.  There currently isn't a facility to force discounts, though it wouldn't be hard to add.

**Comment by timotheev** [comment]
Thank you very much.
