### ISSUE TITLE
scoring fragments (n-grams) using the Python wrapper

### ISSUE THREAD

**Issue by dylanbfox** [kpu/kenlm#78]
I'm trying to get the probability of an n-gram in a language model using the Python wrapper. I came across the paper [Language Model Rest Costs and Space-Efficient Storage](http://kheafield.com/professional/edinburgh/rest_paper.pdf) after finding [this post online](http://moses-support.mit.narkive.com/l4sZUwqy/get-the-probability-of-a-given-n-gram-in-a-language-model).

I've combined a model of order 1, 2, 3, and 4 but after doing some testing it turns out that `bin/fragment` returns different scores than interrogating the model via the `model.score("fragment", bos=False, eos=False)` method.

Is there a way to get the accurate fragment score from within the Python wrapper?

**Comment by kpu** [comment]
There is currently no facility to get fragment scores from the Python API.  The cleanest API would be to wrap RuleScore from left.hh.

**Comment by HappyShadowWalker** [comment]
thi

> There is currently no facility to get fragment scores from the Python API. The cleanest API would be to wrap RuleScore from left.hh.

hi , I want to know ,is it supported for  this feature in python

**Comment by kpu** [comment]
Answer is still the same.  Looking forward to your pull request.
