### ISSUE TITLE
Cannot install kenlm | Python 2.7

### ISSUE THREAD

**Issue by ReiSchneider** [kpu/kenlm#80]
I tried install kenlm using pip but I get these error

C:\Users\acer>pip install https://github.com/kpu/kenlm/archive/master.zip
Collecting https://github.com/kpu/kenlm/archive/master.zip
                                                                Downloading https://github.com/kpu/kenlm/archive/master.zip (517kB)
    100% |################################| 522kB 409kB/s
Installing collected packages: kenlm
  Running setup.py install for kenlm ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\acer\\appdata\\local\\temp\\pip-kmbp9u-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\acer\appdata\local\temp\pip-mj_m_d-record\install-record.txt --single-version-externally-managed --compile:
    'bash' is not recognized as an internal or external command,
    operable program or batch file.
    'bash' is not recognized as an internal or external command,
    operable program or batch file.
    'bash' is not recognized as an internal or external command,
    operable program or batch file.
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\util
    creating build\temp.win32-2.7\Release\lm
    creating build\temp.win32-2.7\Release\util\double-conversion
    creating build\temp.win32-2.7\Release\python
    C:\Users\acer\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -IC:\Python27\include -IC:\Python27\PC /Tputil\bit_packing.cc /Fobuild\temp.win32-2.7\Release\util\bit_packing.obj -O3 -DNDEBUG -DKENLM_MAX_ORDER=6
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    bit_packing.cc
    .\util/bit_packing.hh(30) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\acer\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\acer\\appdata\\local\\temp\\pip-kmbp9u-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\acer\appdata\local\temp\pip-mj_m_d-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\acer\appdata\local\temp\pip-kmbp9u-build\

I reinstall pip and bash for windows 10 but still can't install kenlm

**Comment by kpu** [comment]
Windows is supported only on a contributor basis.  

The bash commands failing should be fine.  It just means you won't get gz/bz2/xz decompression support which I doubt you have the libraries for anyway.  A cross-platform test would be nicer than the bash g++ tests it's currently using.  

Visual studio has support for stdint.h since the 2010 version: https://codeyarns.com/2010/04/13/visual-studio-2010-stdint-h/ https://msdn.microsoft.com/en-us/library/323b6b3k.aspx

**Comment by ReiSchneider** [comment]
So does that mean I won't be able to install kenlm on my python 2.7? 

I don't understand what I should do with the stdint.h file

**Comment by kpu** [comment]
http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

Here's a few options.  Pick one:
- Download https://raw.githubusercontent.com/mattn/gntp-send/master/include/msinttypes/stdint.h and add it to your compiler's include path.  
- Make a simpler header that just has the int8_t, int16_t, int32_t, int64_t, and unsigned definitions, add it to util/, and replace the include statements to refer to that header.
- Search and replace `#include <stdint.h>` with `#include <boost/cstdint.hpp>`.  
- Use a compiler released in the past 7 years.

**Comment by ReiSchneider** [comment]
I'm sorry, I'm really new to this, how do you do

"Download https://raw.githubusercontent.com/mattn/gntp-send/master/include/msinttypes/stdint.h and add it to your compiler's include path."

**Comment by kpu** [comment]
Don't know, I have neither windows nor visual studio. Have fun googling.

**Comment by numericlee** [comment]
@ReiSchneider  I suggest starting over and reinstalling in a virtual environment using the CMAKE process
https://kheafield.com/code/kenlm/ . I  successfully installed on  Windows10 Bash Py2.7 Boost

**Comment by thuvh** [comment]
py2 is dead, i think we should move to using py3

**Comment by orrburgel** [comment]
did anyone solved this?

**Comment by orrburgel** [comment]
Why did you closed this when I asked this is rude

**Comment by ReiSchneider** [comment]
> Why did you closed this when I asked this is rude

This was way back 2017, it wasn't solved. I no longer want it to notify
