### ISSUE TITLE
kenlm Using slower read() instead of mmap()

### ISSUE THREAD

**Issue by ZhenhuaTian** [kpu/kenlm#81]
while training report:
=== 1/5 Counting and sorting n-grams ===
File /dev/pts/12 isn't normal.  Using slower read() instead of mmap().  No progress bar.
training sample text size about 16M

similar issue see: 
http://thread.gmane.org/gmane.comp.nlp.moses.user/12524

**Comment by kpu** [comment]
lmplz reads training data from stdin. You haven't redirected stdin from a file so it is reading input from the console.

Typically you want lmplz -o 5 <data.txt

On March 16, 2017 3:19:19 AM GMT+01:00, ZhenhuaTian <notifications@github.com> wrote:
>while training report:
>=== 1/5 Counting and sorting n-grams ===
>File /dev/pts/12 isn't normal.  Using slower read() instead of mmap(). 
>No progress bar.
>training sample text size about 16M
>
>similar issue see: 
>http://thread.gmane.org/gmane.comp.nlp.moses.user/12524
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kpu/kenlm/issues/81

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ZhenhuaTian** [comment]
Issue has been resolved.

3x a lot！

 

发件人: Kenneth Heafield [mailto:notifications@github.com] 
发送时间: 2017年3月16日 16:29
收件人: kpu/kenlm
抄送: ZhenhuaTian; Author
主题: Re: [kpu/kenlm] kenlm Using slower read() instead of mmap() (#81)

 

lmplz reads training data from stdin. You haven't redirected stdin from a file so it is reading input from the console.

Typically you want lmplz -o 5 <data.txt

On March 16, 2017 3:19:19 AM GMT+01:00, ZhenhuaTian <notifications@github.com <mailto:notifications@github.com> > wrote:
>while training report:
>=== 1/5 Counting and sorting n-grams ===
>File /dev/pts/12 isn't normal. Using slower read() instead of mmap(). 
>No progress bar.
>training sample text size about 16M
>
>similar issue see: 
>http://thread.gmane.org/gmane.comp.nlp.moses.user/12524
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kpu/kenlm/issues/81

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
