### ISSUE TITLE
encounter BadDiscountException (small sample data)

### ISSUE THREAD

**Issue by ZhenhuaTian** [kpu/kenlm#82]
=== 1/5 Counting and sorting n-grams ===
Reading /home/***/workspace/medical-nlp-platform/data/output/all/XXXXXXXXXX.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 5985 types 2361
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:28332 2:1300158592 3:2437797376 4:3900475648 5:5688194048
/home/work/sofe/kenlm/lm/builder/adjust_counts.cc:60 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
ERROR: 1-gram discount out of range for adjusted count 3: -0.9864292
Aborted

**Comment by kpu** [comment]
That's some really small training data and technically interpolated modified Kneser-Ney isn't properly defined.  You can override this with --discount_fallback.  But I'd really get larger text.
