### ISSUE TITLE
Import Error: Undefined Symbol

### ISSUE THREAD

**Issue by baljeet** [kpu/kenlm#83]
I have been trying to install python package for kenlm. I tried pip on github url, on the tar.gz provided in the readme and even tried pypi-kenlm package.
Every single time, the installation goes fine but i get the same error while importing:
>>> import kenlm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/baljeet/anaconda2/lib/python2.7/site-packages/kenlm.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

How do i solve this? I have been trying this for atleast 2 hours now, any help or pointer would be great.

**Comment by baljeet** [comment]
There is a related stackoverflow issue around 1.5 years old, which is unanswered.
http://stackoverflow.com/questions/31031921/python-not-importing-module-perhaps-gcc-being-used-to-compile-the-python-libra

**Comment by kpu** [comment]
I'm guessing you're on OS X?  Do the binaries compile and run correctly, just not the python interface?  What was anaconda compiled with?  

If you post the output of `rm -rf build; python setup.py build` that will at least tell me how it's being compiled. 

Just a thought: if you edit `ARGS` on line 21 of `setup.py` and add `-std=c++11` it might fix things.

**Comment by baljeet** [comment]
I am on Ubuntu 16.04
Added the log file for 
rm -rf build; python setup.py build
[build.txt](https://github.com/kpu/kenlm/files/859141/build.txt)

**Comment by baljeet** [comment]
Hey, Adding -std=c++11 worked.

Thanks.
