### ISSUE TITLE
How to force to load all binary into memory?

### ISSUE THREAD

**Issue by cmathx** [kpu/kenlm#84]
I have trained a language model about 10G(binary). Now I want to load whole binary file to memory. I tested all the load method such as LAZY, POPULATE_OR_LAZY, POPULATE_OR_READ and PARALLEL_READ. Even method "READ" always took about 8107us only one word. I doubted that all methods have already compute conditional probability when language model is loading. How can i force to load all model into memory, and then to query.

**Comment by kpu** [comment]
Any of `POPULATE_OR_READ`, `PARALLEL_READ`, or `READ` will do that.  I suspect your binary file is already in the disk cache, so reading is really just a matter of mapping the pages into the process, which is fast.
