### ISSUE TITLE
why I use import kenlm cann't success?

### ISSUE THREAD

**Issue by wangyizhen** [kpu/kenlm#86]
Hi,KPU.
why I use import kenlm cann't success?
when I use pip install https://github.com/kpu/kenlm/archive/master.zip.the bash give “successfully install”.But I use import kenlm,it show that ImportError: /home/xxx/anaconda3/lib/python3.5/site-packages/kenlm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE.
Here is my python environment:
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
could you help me solve this problem.
Thanks

**Comment by kpu** [comment]
Try editing this line in setup.py
`ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6']`
to be
`ARGS = ['-O3', '-DNDEBUG', '-DKENLM_MAX_ORDER=6', '-std=c++11']`

**Comment by wangyizhen** [comment]
Thank you very much.
by the way,Could you give me the detail API for the kenlm.
Thanks a lot.

**Comment by kpu** [comment]
See `python/kenlm.pyx` which has pydoc-style documentation.

**Comment by wangyizhen** [comment]
Thanks a lot
