### ISSUE TITLE
Training error!!!

### ISSUE THREAD

**Issue by cdj0311** [kpu/kenlm#94]
=== 1/5 Counting and sorting n-grams ===
Reading /data/home/chendajun/egs/lm/data.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 1944718 types 25591
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:307092 2:37540802560 3:70389006336
/data/home/chendajun/tools/kenlm/lm/builder/adjust_counts.cc:52 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 3-grams with adjusted count 2 because we didn't observe any 3-grams with adjusted count 1; Is this small or artificial data?
Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback

Aborted

**Comment by kpu** [comment]
Try deduplicating the input. To override this error for e.g. a class-based model, rerun with --discount_fallback
