### ISSUE TITLE
Error in estimating discount rate

### ISSUE THREAD

**Issue by cuhkebook** [kpu/kenlm#95]
My toy corpus is [update]
i am a boy
i am a small children
i am a small children
a small children like me
a small children
who are you
a small world
a small world
it is a small world
this is it
this is it
this is it
i have a love
i have a love
i have a love
make a fire
make a fire
make a fire
i am hero
i am hero
i am hero
who are
who are
who are
language model
language model
language model
language model
language model
girl model
girl model
boy model
boy model
men eater us
lady love dress bat
lady love dress bat

The error said the discount cannot be found.  Does the corpus need to include all unigram and bigram first?

Error msg:
adjust_counts.cc:60 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
ERROR: 2-gram discount out of range for adjusted count 2: -0.5

**Comment by kpu** [comment]
Yep, Kneser-Ney is not always defined, especially for toy corpora.  It expects to have a more natural rate of singletons.
