### ISSUE TITLE
can't install on ARM64 (arm8 jetson tx2)

### ISSUE THREAD

**Issue by elpimous** [kpu/kenlm#96]
hello all,
could anyone help ?
Need to install Kenlm on ubuntu 16 64 bits,
on a jetson tx2 (ARM8 64 bits)

at install, produce error : 

util/CMakeFiles/kenlm_util.dir/build.make:230: recipe for target 'util/CMakeFiles/kenlm_util.dir/double-conversion/strtod.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/double-conversion/strtod.cc.o] Error 1
util/CMakeFiles/kenlm_util.dir/build.make:110: recipe for target 'util/CMakeFiles/kenlm_util.dir/double-conversion/cached-powers.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/double-conversion/cached-powers.cc.o] Error 1
util/CMakeFiles/kenlm_util.dir/build.make:206: recipe for target 'util/CMakeFiles/kenlm_util.dir/double-conversion/fixed-dtoa.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/double-conversion/fixed-dtoa.cc.o] Error 1
util/CMakeFiles/kenlm_util.dir/build.make:86: recipe for target 'util/CMakeFiles/kenlm_util.dir/double-conversion/bignum.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/double-conversion/bignum.cc.o] Error 1
util/CMakeFiles/kenlm_util.dir/build.make:62: recipe for target 'util/CMakeFiles/kenlm_util.dir/double-conversion/bignum-dtoa.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/double-conversion/bignum-dtoa.cc.o] Error 1
util/CMakeFiles/kenlm_util.dir/build.make:518: recipe for target 'util/CMakeFiles/kenlm_util.dir/float_to_string.cc.o' failed
make[2]: *** [util/CMakeFiles/kenlm_util.dir/float_to_string.cc.o] Error 1
In file included from /home/nvidia/Downloads/kenlm/util/double-conversion/double-conversion.h:31:0,
                 from /home/nvidia/Downloads/kenlm/util/file_piece.cc:3:
/home/nvidia/Downloads/kenlm/util/double-conversion/utils.h:71:2: error: #error Target architecture was not detected as supported by Double-Conversion.
 #error Target architecture was not detected as supported by Double-Conversion.

please help.
vincent

**Comment by kpu** [comment]
Sorry to the delay; I was out of office.  

I've pulled in the latest version of double-conversion but I'm not sure they added arm64.  

Can you take look at https://github.com/google/double-conversion/blob/master/double-conversion/utils.h#L60 run the test and tell me/them which category arm64 falls into, as well as an appropriate preprocessor macro?

**Comment by elpimous** [comment]
Hello kpu 
It's working thank you very much
