### ISSUE TITLE
create french kenlm model with cmusphinx.lm converted in arpa

### ISSUE THREAD

**Issue by elpimous** [kpu/kenlm#97]
hello all,
Trying to create a Kenlm model for french, to use with Deepspeech.
However, I encounter some problems.
I converted my cmusphinx french.lm model to a french.arpa model.
looks like this : 

> \data\
> ngram 1=515
> ngram 2=6849
> ngram 3=38777
> 
> 
> \1-grams:
> -3.8356 &}ei -0.2379
> -3.8356 &}ei|ei -0.2379
> -2.5134 '}_ -0.5562
> -3.8356 '}| -0.2379
> -2.7564 (|1}_ -0.8814
> -1.8313 (}_ -1.3401
> -3.8356 (}aa|yy -0.2379
> -3.8356 (}ai|dd -0.2379
> -3.8356 (}bb|ll -0.2379
> -3.3585 (}ei -0.7150
> -3.8356 (}gg|rr -0.2379
> -3.0575 (}ii -0.7150
> ...

But, can't create a kenlm model.
Could anyone help .
Thanks, Vincent

**Comment by kpu** [comment]
And the error message was?

**Comment by elpimous** [comment]
@kpu 
Thanks for quick answer, Kenneth,

I did this command : 
>
> /usr/local/bin$ lmplz --text /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/train/train_corrected.txt --arpa /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/train/train.arpa --o 3
> === 1/5 Counting and sorting n-grams ===
> Reading /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/train/train_corrected.txt
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ****************************************************************************************************
> Unigram tokens 5773 types 765
> === 2/5 Calculating and sorting adjusted counts ===
> Chain sizes: 1:9180 2:2291588864 3:4296729600
> Statistics:
> 1 765 D1=0.601695 D2=1.18067 D3+=1.64619
> 2 2710 D1=0.757163 D2=1.16243 D3+=1.837
> 3 3649 D1=0.75365 D2=1.31782 D3+=1.51423
> Memory estimate for binary LM:
> type     kB
> probing 147 assuming -p 1.5
> probing 165 assuming -r models -p 1.5
> trie     64 without quantization
> trie     41 assuming -q 8 -b 8 quantization 
> trie     62 assuming -a 22 array pointer compression
> trie     40 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
> === 3/5 Calculating and sorting initial probabilities ===
> Chain sizes: 1:9180 2:43360 3:72980
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ####################################################################################################
> === 4/5 Calculating and writing order-interpolated probabilities ===
> Chain sizes: 1:9180 2:43360 3:72980
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ####################################################################################################
> === 5/5 Writing ARPA model ===
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ****************************************************************************************************
> Name:lmplz	VmPeak:6580132 kB	VmRSS:5168 kB	RSSMax:1486416 kB	user:0.728	sys:0.792	CPU:1.52252	real:1.53589
> 

and trying this produces errors : 

import kenlm
model = kenlm.Model('/home/nvidia/Downloads/modele_lourd/model.arpa ')

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "kenlm.pyx", line 117, in kenlm.Model.__init__ (python/kenlm.cpp:2242)
> IOError: Cannot read model '/home/nvidia/Downloads/modele_lourd/model.arpa ' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /home/nvidia/Downloads/modele_lourd/model.arpa )
> 

the model looks like this :

> 
> \data\
> ngram 1=765
> ngram 2=2710
> ngram 3=3649
> 
> \1-grams:
> -3.4439821	<unk>	0
> 0	<s>	-0.80434245
> -0.90620524	</s>	0
> -2.5123882	qui	-0.21370335
> -2.046849	est	-0.2474989
> -1.8848407	alfred	-0.35783795
> -2.3081791	mon	-0.19704749
> -2.9106848	robot	-0.17406349
> -2.3787863	ce	-0.33474594
> -2.706342	petit	-0.17445114
> -3.065842	noir	-0.12081045
> -1.331467	et	-0.2686208
> -3.065842	blanc	-0.2130128
> -3.065842	toc	-0.17375363
> -3.2952147	là	-0.12081045
> -1.4104223	ou	-0.25830334
> -3.2952147	habites-tu	-0.12081045
> -2.0841043	en	-0.18738198
> -3.2952147	moment	-0.12081045
> -2.146765	que	-0.2836968
> -2.046849	tu	-0.29928753
> -3.2952147	habites	-0.12081045
> -3.2952147	résides	-0.12081045
> -3.065842	où	-0.12081045
> -2.9106848	aujourd'hui	-0.33795154
> -3.1790767	aimes-tu	-0.12081045
> -2.029355	le	-0.17109837
> -3.2952147	sexe	-0.12081045
> -3.065842	ami	-0.16446932
> -3.2952147	aimes	-0.12081043
> ...
> \end\

An idea ?

**Comment by elpimous** [comment]
Ok. My fault. After a binary conversion, it works.

**Comment by kpu** [comment]
The order is how long you want your n-grams to be.  You'll probably want low order and no prune for a small corpus.

**Comment by elpimous** [comment]
Thanks a lot, Kpu
