### ISSUE TITLE
how to mix two language model like the option -mix-lm in SRILM

### ISSUE THREAD

**Issue by liangnet** [kpu/kenlm#98]
Hi Ken, thanks for your significant efforts on this project. I face the problem that I cannot train my model of 2 million words due to limited instance resource (4 core 30G diskspace on AWS EC2). Therefore, I want to train individual model for each training set first and than use the option -mix-lm in SRILM to interpolate them to one final model. However, while I tried the --interpolation_unigram and --intermedia, it seems to be not able to work? Can you help me?

**Comment by liangnet** [comment]
Maybe I know how incrementally train language model. 

lmplz -o 5 --intermediate all --arpa fina.arpa < set1.txt
lmplz -o 5 --intermediate all --arpa fina.arpa < set2.txt
lmplz -o 5 --intermediate all --arpa fina.arpa < set3.txt
....

**Comment by kpu** [comment]
It's going to cost you more AWS credits to build them one at a time and interpolate than it will to build it all at once with a larger disk attached.  Log-linear interpolation is slow.  And since you have to have all the component models, peak disk usage will be larger.  

Nonetheless, here's how to do it.  Install Eigen and compile with it installed.  
```bash
lmplz -o 5 --intermediate set1.intermediate <set1.txt
lmplz -o 5 --intermediate set2.intermediate <set2.txt
lmplz -o 5 --intermediate set3.intermediate <set3.txt
interpolate -m set{1,2,3}.intermediate -t tuning.txt
```

**Comment by liangnet** [comment]
Thanks for your kindly help. Now, I utilized command lmply to get intermediate files for each data set successfully. However, when I use the command as 

> interpolate -m set1.intermedate set2.intermediate set3.intermediate -t text.txt

where the text is the file to tune on text file with one sentence per line, all the probabilities and penalties are 0 and NaN, respectively. Only the arpa header (i.e. \data\) seems to be correct 
. If I use command as 

> interpolate -m set1.intermedate -t text.txt

the probabilities and penalties seem to be correct but the tokens appeared in the tune file are gone~ I just leave a simple sentence to tune.

**Comment by pdcoded** [comment]
@liangnet @kpu can you please show me the format of text.txt

**Comment by VIKRAMKOUNDINYA** [comment]
Hey Ken ,
I'm unable to find interpolate command.I have installed  kenLm and Eigen as described in the readme file and also I have installed SRILM toolkit. Please let me know if I missed anything. Thankyou in advance.
